### ISSUE TITLE
Sprint 1 Team 3: Enemies Feature

### ISSUE THREAD

**Issue by nikmatha** [UQdeco2800/2021-studio-6#10]
### **Description** 
Add basic enemies to the game, including enemy movement, attacking the player, spawning, basic sprite work

During gameplay enemies will give the player extra challenges and increased difficulty - it’s not just about reaching the end of the level, you also need to do so safely

In the final product, this will be used in gameplay for every level, and forms a baseline for character and enemy interaction. 

### **Examples / Sub Feature Component** 
3 minimum types of enemies, but aiming for 4 types of enemies
1. Basic enemy - short range attacks
2. Basic enemy - longer range attacks
3. Smaller enemy, but fast with low damage. Difficult to dodge, but blows are not critical
4. Large enemy, but slow with high damage. Easy to dodge, but blows can be critical 

### **Dependencies** 
Level Management #7   - losing condition animation
Player #8  - the interaction between enemy and player will overlap, specifically in attacking and dodging. camera movement will overlap
Environment #6  - the enemy’s interaction within the environment and how it moves in the space e.g. does it have room to jump

### **Milestones**

**Programming**

- [x] Basic enemy - short range attacks
- [x] Basic enemy - longer range attacks
- [x] Smaller enemy, but fast with low damage. Difficult to dodge, but blows are not critical
- [x] Large enemy, but slow with high damage. Easy to dodge, but blows can be critical

**Design**

- [x] Make placeholder for each type of enemy: 4 types of enemies as seen above (20th aug)
- [x] Create rough design of each of the basic enemies (Tuesday 24th aug)
- [x] Decide on the attacks of each of the enemies based on their design (Wednesday 25th aug)
- [x] Brief implementations of enemies : 4 types of enemies (Wednesday 25th aug)

Due Date: 4pm September 2nd 

### **Documentation**
Will be updated.

### **Members**
Matthew Holloway (@yourlow)
Niklas Matha (@nikmatha)
Jade Taylan (@jadeomikaela)
Hamish Killen (@Hamish-Killen)
Liyang Yu (@quarzt-c)

**Comment by tommps** [comment]
Not sure if you guys have worked on this yet, but the current enemies will attack once then not attack again until the hitboxes recollide, so the player can safely sit on top of the enemy and not take damage.

**Comment by Bluehalomango** [comment]
A point I thought I'd just bring up is incorporating player feedback into enemy interaction. In particular, at the moment there is no way for the player to identify what kind of health an enemy has, how much damage they've taken, etc. While this isn't directly a problem, it can make combat more frustrating and difficult as you are fighting blind in this regard. Have you thought about trying to reflect the enemy state in any way? 

For instance, you could change sprites for damaged enemies or if collaborate with Team 1, you could try and look at implementing a health bar for each enemies. Obviously these are just ideas so y'all can go with whatever but I feel that, as the player, having some way of identifying what state the enemy is in would greatly improve the combat experience. At the moment, you just kind of keep attacking until they die. Additionally, larger enemies, and later minibosses/bosses, will feel more intimidating and impactful if there is a way to meaningfully see how strong they are other than just a large sprite.

**Comment by nikmatha** [comment]
> A point I thought I'd just bring up is incorporating player feedback into enemy interaction. In particular, at the moment there is no way for the player to identify what kind of health an enemy has, how much damage they've taken, etc. While this isn't directly a problem, it can make combat more frustrating and difficult as you are fighting blind in this regard. Have you thought about trying to reflect the enemy state in any way?
> 
> For instance, you could change sprites for damaged enemies or if collaborate with Team 1, you could try and look at implementing a health bar for each enemies. Obviously these are just ideas so y'all can go with whatever but I feel that, as the player, having some way of identifying what state the enemy is in would greatly improve the combat experience. At the moment, you just kind of keep attacking until they die. Additionally, larger enemies, and later minibosses/bosses, will feel more intimidating and impactful if there is a way to meaningfully see how strong they are other than just a large sprite.

Yeah I think it would be good to have a some kind indication of how much health the enemy has. After a quick search, I found this https://www.curseforge.com/stardewvalley/mods/health-bars but that is just an example of what it could look like.

**Comment by 25Ericcheong** [comment]
Just wanted to let you guys know (if you've missed discord):
- I've created a component so that entities created can be disposed of in game (can be used for all enemies created now too - so player can possibly get rid of enemies now if enemy health is 0 now)
- I've not changed PhysicsMovementComponent cause I think you guys must have changed it to make some enemies move faster than the rest so I'll integrate that into my code so the bullets can move faster later on.
