### ISSUE TITLE
Player Task: User Testing - HUD

### ISSUE THREAD

**Issue by tommps** [UQdeco2800/2021-studio-6#101]
# **Description**
**Task:** Player User Testing
**Feature:** #61
 
Completion of user tests in order to gain an understanding of how the player interprets the HUD system and the information within, including: dash cooldown bar, health bar, item signifiers, ammo amount. This testing will also be used to gain an understanding of the best position to place the HUD components on the screen. Testing specifics will be included in the wiki testing document.
   
# **Milestones**
- [x] Writing up a testing plan (Sep 12)
- [x] Performing test plan on a first user (Sep 15)
- [x] Performing test plan on a second user (Sep 15)
- [x] Performing test plan on a third user (Sep 15)
- [x] Evaluating and applying testing results (Sep 15)
**Completion Deadline:** Sep 15
 
# **Documentation**
- [User Testing Player: HUD Elements and Placement](../../2021-studio-6/wiki/User-Testing-Player:-HUD-Elements-and-Placement)
 
# **Member**
- Caitlin Thompson (@tommps) (Caitlin)
