### ISSUE TITLE
Player Task: User Testing Player, Weapon & Item Designs

### ISSUE THREAD

**Issue by tommps** [UQdeco2800/2021-studio-6#102]
# **Description**
**Task:** Player User Testing
**Feature:** #61 
 
Completion of user tests in order to gain an understanding of how the player perceives the player and item designs. Important in order to ensure the player has the correct experience with the game while ensuring the player understands the elements of the game.
   
# **Milestones**
- [x] Writing up a testing plan (Sep 12)
- [x] Performing test plan on a first user (Sep 15)
- [x] Performing test plan on a second user (Sep 15)
- [x] Performing test plan on a third user (Sep 15)
- [x] Evaluating and applying testing results (Sep 15)
**Completion Deadline:** Sep 15
 
# **Documentation**
- [User Testing Player: Player, Weapon and Item designs](../../2021-studio-6/wiki/User-Testing-Player:-Player,-Weapon-and-Item-designs)
 
# **Member**
- Caitlin Thompson (@tommps) (Caitlin)
