### ISSUE TITLE
Player Task: Player Items/Inventory Design

### ISSUE THREAD

**Issue by ydiannaj** [UQdeco2800/2021-studio-6#107]
# **Description**
**Task:** [Player Items/Inventory Design]
**Feature:** Sprint 2 Team 2: Item/Inventory Feature [Player](#68)

Some sprites of items/inventory will be generated. The design will facilitate animation/virtual feedback and correspond to directional melee, modular melee, player abilities, ranged attack and ammo, and interface animations. The items will include a dagger, a sword, an axe, a firecracker, a torch, a bandage, and coins. Each of them will be created with multiple frames.

# **Items**
- [x] Sword
- [x] Dagger
- [x] Axe
- [x] Firecracker and explosion
- [x] Torch
- [x] Bandage

# **Examples**
![image](https://user-images.githubusercontent.com/62837203/133178386-d4c20127-db17-4f24-a843-96be63c65b6c.png)
![image](https://user-images.githubusercontent.com/62837203/133178397-6c48832e-5cd8-4f24-be62-b926eb26b662.png)
![image](https://user-images.githubusercontent.com/62837203/133178415-afd2acf0-ee1d-49e6-9cbf-94293e197623.png)

# **Milestones**
List of steps that need to be completed for this task.
- [x] Complete the player sprite with armor (7 Sep)
- [x] Weapon and item place holders (9 Sep)
- [x] Different frames of each item for animation (11 Sep)
- [x] Sprite sheets for each item and the player (12 Sep)
 
**Completion Deadline:** 13/09

# **References**
https://www.slynyrd.com/blog/2018/9/8/pixelblog-9-melee-attacks

https://graphicriver.net/item/pixel-art-explosions/22425052?irgwc=1&clickid=Try2ufxjaxyIW61RFB3bSQHqUkBQE22323EVXs0&iradid=275988&irpid=1257950&iradtype=ONLINE_TRACKING_LINK&irmptype=mediapartner&mp_value1=&utm_campaign=af_impact_radius_1257950&utm_medium=affiliate&utm_source=impact_radius

https://www.redbubble.com/es/i/pegatina/Pixel-Hacha-Normal-de-BenHenry/33713158.EJUG5

# **Member**
- Jing (@ydiannaj) (Jing Yang)
