### ISSUE TITLE
Interface Task - Title screen (Sep. 2nd)

### ISSUE THREAD

**Issue by DancingBrian** [UQdeco2800/2021-studio-6#12]
# **Description**
**Task:** Title Screen
**Feature:** Interface (#9)
 
This will implement the starting title screen with the game logo and initial starting screen. It is essential for this feature to encapsulate the art style and general vibe of the game. 

# **Dependencies**
None
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Draft creation of background art for main page
- [x] Draft creation of title logo design
- [x] Layout positioning of buttons and title
- [x] Starting new game when the "New Game" button is clicked
- [x] Exiting application when the "Quit" button is clicked
- [x] Implementing animating elements in background art
- [x] Allow for resizing of window while keeping elements aligned and correct aspect ratio
- [x] Creation of button design (normal, roll-over, press/release)
- [x] Final version of background art for main page
- [x] Final version of title logo design
- [x] Testing process outlined in testing plan
- [x] Documentation created for title screen
- [x] Creation and implementation of sound effects on button click/rollover
- [x] Creation and implementation of background music (optional)
- [x] Documentation updated for title screen

**Completion Deadline:** Sep 2nd

# **Documentation**
- [Title Screen](https://github.com/UQdeco2800/2021-studio-6/wiki/Title-Screen)
 
# **Member**
- Brian Stewart (@DancingBrian)
- Chris Kang (@Skybluepanda) 
- Laura Johnston (@ScariestWheat)
- Renée (@NightingaleUQ)
