### ISSUE TITLE
Sprint 3 Team 1: Story and NPCs

### ISSUE THREAD

**Issue by ScariestWheat** [UQdeco2800/2021-studio-6#126]
# **Feature: Story and NPCs**
In this sprint, we are extending the story to incorporate more elements and features to create a better player immersion in the storyworld.

## **Justification**
We believe that adding additional story elements during that main gameplay will:
- Create a more realistic and immersive world
- Give clarity of the game objective
- Give additional back story to help the user emotionally connect

### Create a more realistic and immersive world
Currently the gameplay starts with a prologue and finishes with an epilogue, however there are no story elements in between. We believe that giving the user more options to experience story elements throughout the game will make the user feel that they are in a realistic world within the world we have created. One example of this is having other Fireflies that the user meets along reinforces the prologue's statement that many Fireflies have tried to make the journey before the user. We feel that it also breaks immersion if the user enters the safehouse and there are no other fireflies inside, so having NPCs within the safehouse will help keep the world realistic.

### Give clarity of the game objective
From the user testing in sprint 2, users seem to mostly understand the game objective but were confused about some elements. With adding multiple NPCs for the player to talk to, the NPCs will talk more about what the safe haven might be, why it is urgent to get there, who the shadow crawlers are, and what the safehouses are. We will also include some NPCs at the very start of the game that will give the user tips on how to play, similar to a tutorial.

### Give additional back story to help the user emotionally connect
We want the user to feel connected to the world's characters/enemies, and therefore giving more story about the town the user has fled from, or the friends people have lost along the way, will help the user connect emotionally with the game.

### Mid Level Scenes
Dialogue and illustration between levels to narrate the story to the player and progress the story. (similar to #74 #75)

#### Level 1 to 2
Story between level 1 and level 2. Moving from the city area to the forest area. Dialogue and illustration briefly describing what the forest area looks/feels like.

#### Level 2 to 3
Story between Level 2 and 3. Leaving the forest area and moving into the dock/beach level. Dialogue and illustration describing the environment, and a description of the boss.

### NPCs
Non Player Characters that the player can interact with for various benefits and story snippets. To interact with the NPC, the user will be able to go up to an NPC and press the spacebar. When interacting, the NPC will speak to the player using the dialogue box feature within the game. We plan to create NPCs at the following locations:
* The start of level 1 to help the player understand how to play the game (like a tutorial)
* An NPC near the end of the first level
* A recurring NPC in the first safehouse
* An NPC at the start of the second level
* A recurring NPC at the start of level 3

## **Dependencies**
- [x] SafeHouse NPC - safehouse implementation and how to incorporate the extra NPCs (#125)
- [x] Level 1 - How the safe zone at the beginning in implemented, to allow for tutorial space (#123)

# **Milestones**
- [x] Level 1 to 2 cutscene (Oct 6th) #141
- [x] Level 2 to 3 cutscene (Oct 6th) #142
- [x] NPC Programming (Oct 5th) #143
- [x] NPC: Injured Firefly (Oct 6th) #145
- [x] NPC: Tutorial Town Guide (Oct 6th) #146
- [x] NPC: Recurring NPC (Oct 6th) #147

**Completion Deadline:** 7 October 2021, 4:00pm

# **Extras (optional)**
- [ ] Scrolling text (like a typewriter) when talking to NPCs
- [ ] NPC: Safehouse Firefly two
- [x] NPC: Dead Firefly (Oct 6th) #196
- [ ] NPC: Mid-level Firefly One
- [ ] NPC: Mid-level Firefly Two
- [ ] NPC: Tutorial town person Three
- [ ] NPC: Tutorial town person Four
- [ ] NPC: Captured Shadow Crawler
- [x] Cutscene: Safehouse Introduction #205

# **Documentation**
- [Friendly NPC](https://github.com/UQdeco2800/2021-studio-6/wiki/Sprint-3:-Friendly-NPCs)
- [Friendly NPC design documenation](https://github.com/UQdeco2800/2021-studio-6/wiki/Sprint-3:-Friendly-NPC-Design)
- [Cutscene Design](https://github.com/UQdeco2800/2021-studio-6/wiki/Sprint-3:-Cutscene-Design)

# **Members**
- Brian Stewart (@DancingBrian) (Brian#8636)
- Chris Kang (@Skybluepanda) (Bluepanda#5218)
- Laura Johnston (@ScariestWheat) (ScariestWheat#5492)
- Renée (@NightingaleUQ) (Renée)
- Joseph (@implex001) (implex001#2331)
- Suhas (@suhasudupaa) (Huxley#5371)
