### ISSUE TITLE
Level 1 - Difficulty and Length Adjustment

### ISSUE THREAD

**Issue by zhangyijia97** [UQdeco2800/2021-studio-6#127]
# **Description**
**Task:** [Difficulty and Length Adjustment](#127).
**Feature:** [Level 1](#123)
 
The length and difficulty of level 1 has to be adjusted. Level 1 will act as a tutorial, therefore it should introduce each enemy to the player in a way that the player can safe(ish)ly learn that enemy's patterns. Then, once every enemy has been introduced, the level can start thowing enemies in various combinations at the player to challenge them, with a final challenge blocking the way to the safehouse.

In addition, a tutorial screen telling the player what the controls are, or some other way of teaching the player the controls is needed.
 
## **Example (optional)**
 
# **Dependencies**
- [ ] Tutorial screen summarising the controls is needed (#149)
 
e.g.

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] User testing (Sep. 27)
- [x] Adjustment of level difficulty according to feedback/additional testing (Sep. 29)
- [x] Finished level 1 difficulty adjustment (Sep. 30)
 
**Completion Deadline:** Sept. 30

 
# **Documentation**
- [Main description of feature](../../wikis/page1)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
