### ISSUE TITLE
Task team 3: Boss Design

### ISSUE THREAD

**Issue by Hollycatsoulis** [UQdeco2800/2021-studio-6#128]
# Description

## Examples/ SubFeature component
- [ ] In the water, front view or side view, what will it shoot, how do we attack it, how do we kill it, head or other body parts come out of the darkness to remove need to animate whole body 

# Dependencies
- [ ] Team 5 Level 3 design
- [ ] Team 3 

# Milestones:
- [x] Initial Mockup/brainstorm (20th september)
- [x] Mockup
- [x] User Testing
- [x] Initial design
- [ ] Further Testing
- [ ] Final design 

# Documentation 

## Extra

# Members

Holly Catsoulis @Hollycatsoulis 
Jade Taylan @jadeomikaela 
Crystal Yu @quartz-c
