### ISSUE TITLE
Level 2 - Difficulty and Length Adjustment

### ISSUE THREAD

**Issue by zhangyijia97** [UQdeco2800/2021-studio-6#131]
# **Description**
**Task:** [Difficulty and Length Adjustment](#131).
**Feature:** [Level 2](https://github.com/UQdeco2800/2021-studio-6/issues/150)
 
The length and difficulty of level 2 should be adjusted.  Level 2 is where the game really starts. Accordingly, both the length and difficulty of the level should ramp up somewhat compared to level 1.  

There will be some user testing from other people to improve and adjust the level 2 game area changes if needed.
 
# **Dependencies**
- [x] A redesign of level 2 is needed before the fine-tuning can begin (#152)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] User testing (Sep. 30)
- [x] Adjustment of level difficulty according to feedback/additional testing (Oct. 1)
- [x] Finished level 2 difficulty adjustment (Oct. 2)
 
**Completion Deadline:** Oct. 2
 
# **Documentation**
- [Level 2 Wikipage](https://github.com/UQdeco2800/2021-studio-6/wiki/Level-2)

# **Member**
- Hai (@kainphoton) (Anh Hai Ho Chapman) 
- Yunho (@ayhlee) (Yunho Lee)
- Yijia (@zhangyijia97) (Yijia Zhang)
- Patrick (@Lumin-cider) (Cheng-Yu Lin)
- James (@BungyStudios) (James Kebung Chen-Smith)
