### ISSUE TITLE
Sprint 3: Team 2: Sound Effects (Player centric)

### ISSUE THREAD

**Issue by tommps** [UQdeco2800/2021-studio-6#137]
# **Description**
To ensure the player is both immersed within the game world and is aware of what they are doing at all times, sound effects will be included alongside the current animations. This is important both in terms of a players enjoyment and within allowing the player to suspend reality and interact within the game.

## Sub Feature/Component
- Background music while within the shop screen
- Volume control for music and sound effect
- Sound effects for player: attacking (each weapon), dashing, getting hurt
- Sound effects for items: using them
- Sound effects for abilities: activation and possibly when the cooldown is over
 
# **Milestones**
- [x] Player sounds: getting hurt (23/09)
- [x] Item sounds: picking up/use of bandage (23/09)
- [ ] Weapon sounds: swinging axe/dagger/sword (29/09)
- [x] Ability sounds: activation of each ability (1/10)
- [x] Finalisation of Documentation (6/10)
- [x] #206 (7/10)

Sprint Due date = 7/10

# **Extras**
- Shop background music

# **Documentation**
- [TBD](../wiki/)
 
# **Members**
- Anthony Chiam (@ultimate1112)

**Comment by tommps** [comment]
EOS
