### ISSUE TITLE
Safehouse Task: Shop popup box triggering and item organization

### ISSUE THREAD

**Issue by 25Ericcheong** [UQdeco2800/2021-studio-6#138]
# **Description**
When player collides with shop keeper in safehouse (will use placeholder for now), a popup box will appear which will basically function as a shop. This shop will give player the opportunity to spend their coins collected throughout the game. This shop will essentially look similar to the examples included in this task ticket (for reference) where there will be a fully drawn shopkeeper character on the left (which will take 1/3 of the popup box space) and items (along with its description that will take up 2/3 of the popup box space) for which player can purchase with their coins. 
 
## **Examples**
- **Popup box layout:** Ideally, item images, placement of shopkeeper and description of item clicked (this will be displayed differently when an item is clicked by player - this has been brought forward to a different ticket) should be laid out similarly to images shown in this same ticket
- **Hover over image effect:** Whenever mouse is hovered over any of the item images, there should be a clear indication that such image can be clicked (a white border appearing when image is being hovered over for eg.)
- **Description of item:** User may want more information on item, and this can be done (hopefully it would sufficiently be intuitive) by clicking on the image of the item
- **Trigger popup box:** Popup box will be triggered when player collides with NPC (shopkeeper) in safehouse 

# **Dependencies**
- #68 
- #61 
 
# **Milestones**
- [x] Look into implementation of `PauseMenuDisplay.java` and incorporate code design to implement popup box (or at least plan to) (20/09)
- [x] Plan organization of table arrangement prior to implementation (ensure approved by relevant members) (20/09)
- [x] Popup box to appear when player collides with shopkeeper NPC (20/09)
- [x] Title of popup box and relevant information that player needs (coins left and perhaps player's front view - as shown in image attached to this task ticket) (21/09)
- [x] Item images will be placed in envisioned organization (and probably used as buttons) (21/09)
- [x] ~Hover effect for buttons (perhaps border color will change or something to provide feedback to player)~ If buttons are clicked, different image (oriented differently or highlighted with borders) will be shown. For now, images will need to be polished for better visuals (21/09)
- [x] ~Clicking item images will display description for item clicked and how much it would cost (if player does want to buy)~ Brought forward to different task ticket. This ticket mainly focuses on organization and proper placement of all relevant information that is expected to be on the popup box (22/09)

# **Documentation**
- [Wiki ](https://github.com/UQdeco2800/2021-studio-6/wiki/Safehouse-Overview)
 
# **Reference/Inspiration**
![Envisioned item organization](https://user-images.githubusercontent.com/55186326/133880082-21e21e4d-a3d0-4bab-a9d8-418c7bc2763f.png)

![Fully drawn character placement on the left](https://user-images.githubusercontent.com/55186326/133880099-1207a9f2-7f1d-483d-8b7b-cda2611c6ce5.png)

# **Planning for shop popup box**
![Shop popup box initial design](https://user-images.githubusercontent.com/55186326/133910458-ee2f59ca-20d9-41bb-a4e4-e41270293b9c.PNG)
Place holders being used as shop keeper image on the left

# **Implemented shop popup box (for now)**
![Current popup box implemented](https://user-images.githubusercontent.com/55186326/133961685-47001879-eb05-49cc-bbbc-37d69d85b15a.PNG)

# **Members**
- Eric Cheong Kai Kit (@25Ericcheong) (Eric)
