### ISSUE TITLE
Interface Task - Dialogue box shell (Sep. 2nd)

### ISSUE THREAD

**Issue by DancingBrian** [UQdeco2800/2021-studio-6#14]
# **Description**
**Task:** Design box shell
**Feature:** Interface (#9)
**Branch:** [S1T1-Feature/DialogueBox](https://github.com/UQdeco2800/2021-studio-6/tree/S1T1-Feature/DialogueBox)
 
Design and implement dialogue boxes. A dialogue box will have a background texture, and sounds to complement the dialogue. Font size, spacing and character limits will be considered in the design process. 
DialogueBox inherits from UIComponent and adds methods to display and forward dialogue.
This initial task is to implement the placeholder and main system of dialogue boxes as well as creating a visual style.

 
## **Example**
During a cutscene, a dialogue box appears to tell a story or character speech. (cut scenes to be implemented in later sprints)
The player might stumble upon something within the gameplay and mention something within the story, with a dialogue box appearing on screen.
 
# **Dependencies**
None
 
# **Milestones**
- [x] Initial design of DialogueBox created and documented
- [x] Creation of background texture
- [x] Creation of player portrait asset
- [x] Selection of font
- [x] Method to advance dialogue
- [x] write dialogue (simple intro player exposition)
- [x] Unit tests for DialogueBox
- [x] DialogueBox implemented and tested
- [x] Documentation updated
 
**Completion Deadline:** Aug. 27
 
# **Documentation**
- [Dialogue Boxes](https://github.com/UQdeco2800/2021-studio-6/wiki/Dialogue-Boxes)
 
# **Member**
- Chris Kang (@Skybluepanda) 
- Renée (@NightingaleUQ)
- Joseph (@implex001)

**Comment by implex001** [comment]
All milestones completed
