### ISSUE TITLE
Level 1 to 2 cutscene (Oct 6th)

### ISSUE THREAD

**Issue by DancingBrian** [UQdeco2800/2021-studio-6#141]
# **Description**
**Task:** Level 1 to 2 Scene
**Feature:** Story and NPCs (#126)
Story between level 1 and level 2. Moving from the city area to the forest area. Dialogue and illustration briefly describing what the forest area looks/feels like.

# **Dependencies**
- [Story Overview] How the story is meant to progress based on the studio approved storyline:  (https://github.com/UQdeco2800/2021-studio-6/wiki/Story-Overview)
  
# **Milestones**
- [x] Draft script and storyboard (23/9)
- [x] Finalise script and storyboard (24/9)
- [x] Create visual artwork (29/9)
- [x] Implementation of scene (30/9)
- [x] User Testing (3/10)
- [x] Debugging/feedback fixing (5/10)
- [x] Update story scene design documentation (6/10)
 
**Completion Deadline:** Wed Oct 6
 
# **Extras**
-  Animate visuals
-  Cutscene background music

# **Documentation**
- [Cutscene Design](https://github.com/UQdeco2800/2021-studio-6/wiki/Sprint-3:-Cutscene-Design)
- [Story Overview](https://github.com/UQdeco2800/2021-studio-6/wiki/Story-Overview)
- [Story Scene Design](https://github.com/UQdeco2800/2021-studio-6/wiki/Story-Scene-Design-Documentation)

# **Member**
- Brian Stewart (@DancingBrian) (Brian#8636)
- Laura Johnston (@ScariestWheat) (ScariestWheat#5492)
- Joseph (@implex001) (implex001#2331)
