### ISSUE TITLE
Level 2 to 3 cutscene (Oct 6th)

### ISSUE THREAD

**Issue by DancingBrian** [UQdeco2800/2021-studio-6#142]
# **Description**
**Task:** Level 2 to 3 Scene
**Feature:** Story and NPCs (#126)
Story between Level 2 and 3. Leaving the forest area and moving into the dock/beach level. Dialogue and illustration describing the environment, and a description of the boss.

# **Dependencies**
- [x] Level 3/Final Boss: The terrain design and gameplay of the final level needs to be somewhat completed to allow for the scene to be created (#124)
- [x] [Story Overview] How the story is meant to progress based on the studio approved storyline:  (https://github.com/UQdeco2800/2021-studio-6/wiki/Story-Overview)
  
# **Milestones**
- [x] Draft script and storyboard (23/9)
- [x] Finalise script and storyboard (24/9)
- [x] Create visual artwork (29/9)
- [x] Implementation of scene (30/9)
- [x] User Testing (3/10)
- [x] Debugging/feedback fixing (5/10)
- [ ] Update story scene design documentation (6/10)
 
**Completion Deadline:** Wed Oct 6
 
# **Extras**
-  Animate visuals
-  Cutscene background music

# **Documentation**
- [Cutscene Design](https://github.com/UQdeco2800/2021-studio-6/wiki/Sprint-3:-Cutscene-Design)
- [Story Overview](https://github.com/UQdeco2800/2021-studio-6/wiki/Story-Overview)
- [Story Scene Design](https://github.com/UQdeco2800/2021-studio-6/wiki/Story-Scene-Design-Documentation)

# **Member**
- Brian Stewart (@DancingBrian) (Brian#8636)
- Laura Johnston (@ScariestWheat) (ScariestWheat#5492)
- Joseph (@implex001) (implex001#2331)
