### ISSUE TITLE
NPC Programming (Oct 5th)

### ISSUE THREAD

**Issue by DancingBrian** [UQdeco2800/2021-studio-6#143]
# **Description**
**Task:** NPC Programming
**Feature:** Story and NPCs (#126)
The programming side of interactive NPCs. This class will handle triggers to dialogue, spawning and disposal of NPCs. Dialogue itself will be interfaced through the story manager.

# **Dependencies**
- [x] Spawn safe area: Need to discuss with Team 5 on how they’re implementing the safe area in level 1, and when that’ll be available (#123)
  
# **Milestones**
- [x] NPC Trigger Component (22nd September)
- [x] NPC Display Sprite Component (22nd September)
- [x] NPC Entity Factory (22nd September)
- [x] Create technical documentation for NPC  (24th September)
- [x] NPC Sub categories (22nd September)
- [x] NPC Spawning/Disposal (22nd September)
- [x] Creating unit tests (2nd October)
- [x] User Testing (4th October)
- [x] Finalise technical documentation for NPC (6th October)

**Completion Deadline:** October 5th
 
# **Extras**
- [x] NPC change direction to face the player when the user talks to the NPC
- [x] NPC movement animation/direction component

# **Documentation**
- [Friendly NPCs](https://github.com/UQdeco2800/2021-studio-6/wiki/Friendly-NPCs)

# **Members**
- Brian Stewart (@DancingBrian) (Brian#8636)
- Joseph (@implex001) (implex001#2331)
