### ISSUE TITLE
NPC: Recurring NPC in the safehouse (Oct 6th)

### ISSUE THREAD

**Issue by DancingBrian** [UQdeco2800/2021-studio-6#144]
# **Description**
**Task:** NPC Recurring NPC in the safehouse
**Feature:** Story and NPCs (#126)
Design and implementation of the second and third encounters with the pilot NPC. The second encounter will have the pilot slightly injured, and the third encounter will be with the pilots dead body.

# **Justification**
User testing uncovered that the users did not feel any emotional connections to the friendly NPCs, and therefore they did not have the impact we were expecting. We have attempted to fix this by making a recurring NPC (the pilot), who will be a Firefly as well making the same journey as the player. The multiple encounters will hopefully help create an emotional connection with the user, where they ultimately find the pilot NPCs dead body in the third encounter..

# **Dependencies**
- [x] #143 

# **Milestones**
- [ ] User Testing (Sun 3 Oct)
- [ ] Prototype second encounter NPC design (Mon 4 Oct)
- [ ] Write second encounter NPC Dialogue (Mon 4 Oct)
- [ ] Add Interaction with Entity for the second encounter NPC (Mon 4 Oct)
- [ ] Finalise second encounter NPC design (Mon 4 Oct)
- [ ] Implement second encounter NPC (Mon 4 Oct)
- [ ] Prototype third encounter NPC design (Tue 5 Oct)
- [ ] Write third encounter NPC Dialogue (Tue 5 Oct)
- [ ] Add Interaction with Entity for the third encounter NPC (Tue 5 Oct)
- [ ] Finalise third d encounter NPC design (Tue 5 Oct)
- [ ] Implement third encounter NPC (Tue 5 Oct)
- [ ] Update NPC Documentation (Wed 6 Oct)

**Completion Deadline:** Wed Oct 6

# **Extras**
- [ ] NPC Portrait

# **Documentation**
- [Friendly NPCs](https://github.com/UQdeco2800/2021-studio-6/wiki/Friendly-NPCs)
- [Friendly NPC Design](https://github.com/UQdeco2800/2021-studio-6/wiki/Design:-Friendly-NPC)

# **Members**
- Chris Kang (@Skybluepanda) (Bluepanda#5218)
