### ISSUE TITLE
NPC: Injured Firefly (Oct 6th)

### ISSUE THREAD

**Issue by DancingBrian** [UQdeco2800/2021-studio-6#145]
# **Description**
**Task:** NPC Injured Firefly
**Feature:** Story and NPCs (#126)
Design and implementation of the injured firefly NPC that the character can interact with at the end of level 1 to emotionally immerse the player into the game and it’s story.

# **Dependencies**
- [x] #143 

# **Milestones**
- [x] Prototype NPC design (Thu 23 Sep)
- [x] Write NPC Dialogue (Thu 23 Sep)
- [x] Add Interaction with Entity NPC (Sat 25 Sep)
- [x] Finalise NPC design (Thu 23 Sep)
- [x] Implement NPC (Sat 25 Sep)
- [x] User Testing (Sun 3 Oct)
- [x] Update NPC Documentation (Wed 6 Oct)

**Completion Deadline:** Wed Oct 6

# **Extras**
- [x] NPC Portrait
- [x] NPC asset variation with facing direction

# **Documentation**
- [Friendly NPCs](https://github.com/UQdeco2800/2021-studio-6/wiki/Friendly-NPCs)
- [Friendly NPC Design](https://github.com/UQdeco2800/2021-studio-6/wiki/Design:-Friendly-NPC)

# **Members**
- Renée (@NightingaleUQ) (Renée)
