### ISSUE TITLE
NPC: Recurring NPC (Oct 6th)

### ISSUE THREAD

**Issue by DancingBrian** [UQdeco2800/2021-studio-6#147]
# **Description**
**Task:** Recurring NPC
**Feature:** Story and NPCs (#126)
Design and implementation of the recurring NPC that encounters the player three times: initial tutorial town section, first safehouse, and level 3. The second encounter will have the NPC slightly injured, and the third encounter will be with the NPCs dead body.

# **Justification**
User testing uncovered that the users did not feel any emotional connections to the friendly NPCs, and therefore they did not have the impact we were expecting. We have attempted to fix this by making a recurring NPC (the pilot), who will be a Firefly as well making the same journey as the player. The multiple encounters will hopefully help create an emotional connection with the user, where they ultimately find the pilot NPCs dead body in the third encounter..

# **Dependencies**
- [x] #143 

# **Milestones**
- [x] Prototype NPC design (Mon 27 Sep)
- [x] Write NPC Dialogue (Tue 28 Sep)
- [x] Add Interaction with Entity NPC (Thu 30 Sep)
- [x] Finalise NPC design (Fri 1 Oct)
- [x] Implement NPC (Sat 2 Oct)
- [x] User Testing (Sun 3 Oct)
- [x] Prototype second encounter NPC design (Mon 4 Oct)
- [x] Write second encounter NPC Dialogue (Mon 4 Oct)
- [x] Add Interaction with Entity for the second encounter NPC (Mon 4 Oct)
- [x] Finalise second encounter NPC design (Mon 4 Oct)
- [x] Implement second encounter NPC (Mon 4 Oct)
- [x] Prototype third encounter NPC design (Tue 5 Oct)
- [x] Write third encounter NPC Dialogue (Tue 5 Oct)
- [x] Add Interaction with Entity for the third encounter NPC (Tue 5 Oct)
- [x] Finalise third encounter NPC design (Tue 5 Oct)
- [x] Implement third encounter NPC (Tue 5 Oct)
- [x] Update NPC Documentation (Wed 6 Oct)

**Completion Deadline:** Wed Oct 6

# **Extras**
- [x] NPC Portrait first encounter
- [x] NPC Portrait second encounter
- [x] NPC asset variation with facing direction
- [x] NPC animations (walking)

# **Documentation**
- [Friendly NPC](https://github.com/UQdeco2800/2021-studio-6/wiki/Sprint-3:-Friendly-NPCs)
- [Friendly NPC design documenation](https://github.com/UQdeco2800/2021-studio-6/wiki/Sprint-3:-Friendly-NPC-Design)

# **Members**
- Chris Kang (@Skybluepanda) (Bluepanda#5218)
- Suhas (@suhasudupaa) (Huxley#5371)
