### ISSUE TITLE
Interface Task - Design and implementation of HUD (Sep. 2nd)

### ISSUE THREAD

**Issue by DancingBrian** [UQdeco2800/2021-studio-6#15]
# **Description**
**Task:** Design and implementation of  HUD
**Feature:** Interface (#9)
 
Design and implement the HUD for the main gameplay. Display health and other player stats, as well as other environment statistics determined by #8 and #6. This initial sprint task will focus on the implementation of the static positioning of the HUD elements, with the integration of the statistics from the gameplay to come later in development if time permits. 

 
## **Details**
- **Visual**: Small and out of the way of the main play screen, should be quick and easy to read

 
# **Dependencies**
- [x] Player statistics (#8)
- [x] Environment statistics (#6)
 
 
# **Milestones**
- [x] Determine assets needed for display 
- [x] Plan layout and asset designs
- [x] Implement HUD with placeholders for statistics
- [x] Unit-tests implemented in relation to HUD
- [x] Update Documentation for the HUD
 
**Completion Deadline:** Aug. 30
 
 # **Extras**
- [ ] Link player health to synchronise with health representation on the HUD
- [ ] Link other player statistics to be displayed on the HUD
- [ ] Link environment statistics to be displayed on the HUD
- [ ] Add time placeholder in game, displayed visually as a clock
- [x] Create Wiki for the design documentation
_Extras delayed to early Sprint 2 due to lack of time and understanding of adding animation to the game_

# **Documentation**
- [HUD Design Documentation](https://github.com/UQdeco2800/2021-studio-6/wiki/HUD-Design-Documentation)
 
# **Member**
- Chris Kang (@Skybluepanda) 
- Laura Johnston (@ScariestWheat)
- Renée (@NightingaleUQ)
- Joseph (@implex001)

**Comment by Bluehalomango** [comment]
Hey, we've gone and added a dash ability to the player now and will be creating a pull request for that today (as well as some other stuff). Anyway, at the moment the dash goes on a cooldown timer when the player uses it so we were wondering if it was possible to add a feedback element to the UI to reflect the cooldown timer? There is some more information on the Player Movement wikidoc but let us know what you think.

**Comment by Bluehalomango** [comment]
Another point, I've been talking with Team 3 about a way to represent the enemies health to the player and we were thinking of giving each enemy a health bar. Ultimately though, that falls into your teams field so it might be something to keep in mind with the UI and HUD. I don't know how difficult it would be so maybe talk it out and see what you come to.

**Comment by Skybluepanda** [comment]
Dash cooldown should be pretty easy. I'll look into animating a bar that increases up to ready state. Same for hp bar since it regenerates.

As for enemy hp, it should be easy to simply use smaller version of the player health bar for them when I'm done with the player's health bar.

Thanks for letting me know I'll make changes to fit these needs.
