### ISSUE TITLE
Level 2 - Layout Redesign

### ISSUE THREAD

**Issue by zhangyijia97** [UQdeco2800/2021-studio-6#152]
# **Description**
**Task:** [Difficulty and Length Adjustment](#131).
**Feature:** [Level 2](https://github.com/UQdeco2800/2021-studio-6/issues/150)
 
The layout of level 2 has to be redesigned so that the length and difficulty of the level is appropriate.
 
# **Dependencies**
- [x] Assets needed for the new level 2 (#153)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Level 2 layout planned (matrix x,y grid layout with assets/tilesets inside the cells) (Sep. 27)
- [x] Level 2 implemented with placeholders (Sep. 28)
- [x] Level 2 implemented with finished assets (Sep. 29)
 
**Completion Deadline:** Sep. 29

 
# **Documentation**
- [Level 2 Wikipage](https://github.com/UQdeco2800/2021-studio-6/wiki/Level-2)

# **Member**
- Hai (@kainphoton) (Anh Hai Ho Chapman) 
- Yunho (@ayhlee) (Yunho Lee)
