### ISSUE TITLE
Level 3 - Assets

### ISSUE THREAD

**Issue by zhangyijia97** [UQdeco2800/2021-studio-6#154]
# **Description**
**Task:** [Level 3 assets](#154) 
**Feature:** [Level 3](./151)
 
Design and draw additional assets and tile sets for level 3.

# **Assets**
- Bridge tile sets _(sides matches with grass and water tile sets)_
- Water tile sets _(sides matches with the grass tile sets and bridge)_ 
- Grass tile sets _(grass color more light brown, less green)_
- 2 Withered tree assets _(more brown, less leaves?)_

# **Milestones**
- [x] Grass tile sets (Sep. 29)
- [x] Bridge tile sets (Oct. 2)
- [x] Water tile sets (Oct. 3)
- [x] Withered tree assets (Oct. 4)

**Completion Deadline:** Oct. 4
 
# **Documentation**
- [Main description of feature](../../wikis/page1) (to be updated)

# **Member**
- Hai (@kainphoton) (Anh Hai Ho Chapman) 
- Yunho (@ayhlee) (Yunho Lee)
