### ISSUE TITLE
Safehouse Task: Buying system and include files for loading and updating in popup box

### ISSUE THREAD

**Issue by 25Ericcheong** [UQdeco2800/2021-studio-6#157]
Feature: #125 

# **Description**
With the organization of shop popup box implemented for user visualization as shown in this issue #138 along with the finalized implementation shown attached with this issue as well. This task ticket will primarily focus on the buying and equipping player with the item bought from the shop. In addition to that, it will also include updating the data on the popup box when users click on different items as well. The buying system must be able to have access to player's current state and this will be done by accessing a json file that has all the relevant information. This information will then be used to check certain conditions and dependent on if conditions are met - different feedback text will be produced on the popup box for user's acknowledgement.  
 
## **Examples**
- **Buying system:** Essentially, for player to buy something. Player will need to have sufficient amount of coins for purchasing. If users attempts to purchase an item without sufficient amount of coins, feedback will be produced. Different feedback will be produced when user has sufficient amount of coin to make a purchase
- **Displaying different data variables for different items clicked:** With different items clicked, different description should be displayed to user. This is critical in giving users information that they need to choose the kinds of weapon to purchase and use and be more vary of spending coins needlessly. 
- **Equipping player with bought items:** Upon purchasing items, player state should be updated (file) and should be equipped with correct items bought by player.

# **Dependencies**
- #138
- #158 
 
# **Milestones**
- [x] Preparing and displaying relevant information about items in shop pop up box (change description of items upon clicking and pricing of each item) (21/09)
- [x] Create PlayerState.json file that will be used for testing (if not created yet)  (22/09)
- [x] Load file to test for amount of coins player currently have - test to ensure right values are being loaded  (22/09)
- [x] Display feedback depending on price of items and how much player has in inventory (based on PlayerState.json file) (22/09)
- [x] Upon purchasing, should update ~PlayerState.json file~ player state with updated coins number left (or any other relevant information like having different weapons, or abilities and etc.) (23/09)
- [x] ~Equipping player with items bought (will double check)~. Player can't melee attack in safehouse, so there isn't a need to change this. So this has changed to updating player current state based on what user can see and do in safehouse (23/09)

# **Documentation**
- [Wiki ](https://github.com/UQdeco2800/2021-studio-6/wiki/Safehouse-Overview)

# **Planning for shop popup box**
![Shop popup box initial design](https://user-images.githubusercontent.com/55186326/133910458-ee2f59ca-20d9-41bb-a4e4-e41270293b9c.PNG)
Place holders being used as shop keeper image on the left

# **Implemented shop popup box (for now)**
![Current popup box implemented](https://user-images.githubusercontent.com/55186326/133961685-47001879-eb05-49cc-bbbc-37d69d85b15a.PNG)

# **Members**
- Eric Cheong Kai Kit (@25Ericcheong) (Eric)
