### ISSUE TITLE
Saving Task: Saving system

### ISSUE THREAD

**Issue by SBHATTA19** [UQdeco2800/2021-studio-6#158]
Feature: #125 

# **Description**
Integrating the functionality required for the player to retain their equipment and other player attributes between levels. Player should be able to walk into different environments and avoid the contents of their inventory from being reset. Currently, the player entering a new level or the safehouse resets many of these features.

## **Examples**
- **Buying system:** The player state is stored and updated in the safe house based on the purchases of the player
- **Entering new level:** Upon entering a new level, the existing player data will be loaded into current inventory

# **Dependencies**
- #138
 
# **Milestones**
- [ ] Ability to write the current state into config file within level
- [ ] Ability to alter the config file based on pickups
- [ ] Load config files into the inventory between levels
 **(Extra)** 
- [ ] Allow config files to store various versions of the same weapon allowing upgrades 

# **Documentation**
- [Wiki ](https://github.com/UQdeco2800/2021-studio-6/wiki/Safehouse-Overview)

# **Members**
- Sambit Bhattacharya (@SBHATTA19 ) (Sambit)

**Comment by 25Ericcheong** [comment]
Saving system (which involves creating new config files) and preserving/carrying player states are 2 different things. Would be a better idea to isolate these 2 things separately - if not the file management will be difficult to do later on. Player states will be an internal memory storing kind of thing (created only when game is loaded once [if a new game is started - we load the standard json file that we already have. But if player decides to load a file, player's initial state will be the data loaded from the json file] and continues to tracks and updates when player progresses  throughout game). Saving system will only deal with creating json files to save player's current state. This file can then be loaded and this player state will then be used as player's initial state in game.

**Comment by 25Ericcheong** [comment]
Will no longer be implementing as discussed during studio
