### ISSUE TITLE
Player Task: Environment Collision

### ISSUE THREAD

**Issue by 25Ericcheong** [UQdeco2800/2021-studio-6#16]
# **Description**
**Task:** Environment Collision for Player
**Feature:** Player (#8)

Implementation of interaction between player and environment. 'Environment' currently (for sprint 1) only includes obstacles that are produced throughout the game. Implementation of obstacles would include dimensions that are different from pre-existing ones in game currently, inflicting damage to players or detrimental effects such as decreasing player's movement (if they get too close). Obstacles would comprise of entities with different components to visually look bigger or smaller for player to maneuver around. To impact players by damaging or slowing their movement, event handlers will be placed on player entity in the case when players get too close to specific type of obstacles. 
 
## **Example**
- **Obstacle with different dimensions**: Player will require to walk around obstacles that are different in dimensions throughout the game
- **Obstacles that inflict damage**: Player will receive damage if they get too close to obstacle. This obstacle will also appear different from normal obstacles to magnify the effect of different looking obstacles.
- **Obstacles that impact player movement speed**: Movement speed of player will decrease if player is to cross over such obstacle. Although it is an 'obstacle', player will be able to pass through such obstacle which is different from previous mentioned obstacles. This obstacle should also be designed differently as well.

# **Dependencies**
- Movement speed of player (to be included)
- Obstacle interaction (#3)

e.g.
- [ ] Texture needs to be created for different types of `obstacles`.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Documentation of different obstacles on wiki (Aug. 22)
- [ ] Unit tests implemented for all kinds of obstacles (Aug. 23)
- [ ] Placeholders will be used to represent different obstacles (if texture not available) (Aug. 24)
- [ ] Player interaction with obstacles of different dimensions (Aug. 24)
- [ ] Damage inflicting obstacles on player (Aug. 25)
- [ ] Decrease in movement speed of player crossing over obstacle (Aug. 27)
 
**Completion Deadline:** Aug. 28
 
# **Documentation**
- [Environment Collision Doc](../wiki/Environment-Collision)
 
# **Member**
- Eric Cheong (@25Ericcheong) (Eric)

**Comment by 25Ericcheong** [comment]
Team 4 will take over task.
