### ISSUE TITLE
Player State Task: Preserving, carrying and restoring player's state

### ISSUE THREAD

**Issue by 25Ericcheong** [UQdeco2800/2021-studio-6#168]
Feature: #125 

# **Description**
Integrating the functionality required for the player to retain their equipment and other player attributes between levels. Player should be able to walk into different environments and avoid the contents of their inventory from being reset. Currently, the player entering a new level or the safehouse resets many of these features. The solution to carrying these data is by tracking player's state. This is further elaborated in the examples below. By preserving player's state, the data will be preserved and carried forward (or backward by restoring when/if player dies during game).

## **Kinds of player state that will exist in game**
- Initial player state (when game is loaded by player for the first time or when a game file has been loaded by player. This is the first player state that loads data from json files)
- ~Leaving a game level player state (right before current game level player currently is at is destroyed - a player state is saved in memory. This is where state tracks if any consumables, health, etc. have changed during a game level. This is also used in safehouse to carry over any changed in items that have been purchased to the next game level)~
- Arriving a new game level player state (this is used to track player's progress in game - what level is player currently)

## **Examples**
- **Buying system:** The player state is stored and updated in the safe house based on the purchases of the player. All item purchases made by player (successful ones only) will update player's state when player leaves safehouse.
- **Entering new level:** Upon entering a new level, the existing player state will be loaded - this includes relevant information like player's current wound state, what melee weapon player is carrying currently, item quantity etc.
- **Preserving player state:** Player's state is preserved (checkpoints or so to say) only at the following time - when a specific game level starts (to track initial player state variables and to track which level player is currently at to reset when player dies) and when player leaves a level (this can be leaving safehouse or leaving a specific level to track if any data variables have changed after a level is completed)
- **Player dying:** Based on the mentioned states, player will be reverted to the most recent created state in memory. Example, if player dies midway through in level 2 of game, player will be loaded to the start of level 2 as mentioned along with all items attached as mentioned previously.

# **Dependencies**
- #157 
 
# **Milestones**
- [x] Decide on most applicable design pattern to use for player state management system (Momento + Singleton)
- [x] Apply design pattern into code base
- [x] Checkpoint player state when player finishes a level (track amount consumable items left) and when player starts a new level (track which level player is currently in). Shown via logging for testing purposes
- [x] Carrying player's state and updating player entity object when a game level is destroyed and then created (should visually be reflected on HUD)
- [x] Player taken to closest checkpoint if player dies (resetting to closest checkpoint in game). This will be triggered by clicking a button on game over screen

# **Documentation**
- To be included

# **Members**
- Eric Cheong Kai Kit (@25Ericcheong) (Eric)

**Comment by 25Ericcheong** [comment]
Buying system related to modifying player state when an item is purchased will be done here #157
