### ISSUE TITLE
Task Team 3: Sailboat design

### ISSUE THREAD

**Issue by jadeomikaela** [UQdeco2800/2021-studio-6#169]
# Description

Creation of the sailboat graphic for the player to use to escape into the light, after beating the final boss. This will be made using Piskel. User testing will be done after the first creation of the graphic and improved with the advice give.

# Milestones

- [x] Create first graphic (24th August)
- [x] User testing (25th August)
- [x] Final Graphic (27th August)

# Documentation 

- [x] Document User testing
- [x] Justify design choice

# Members
Jade Taylan @jadeomikaela
