### ISSUE TITLE
Player Feature: Basic Stats

### ISSUE THREAD

**Issue by tommps** [UQdeco2800/2021-studio-6#17]
# **Description**
**Task:** Basic Player Statistics
**Feature:** #8 
 
Implementation of the player statistics will include the defining of the movement speed, attack damage and defence level of the player, alongside providing methods for it to be altered during the game. This will involve the modification of pre-existing player components and events.
Movement speed will act as a modifier to increase/decrease the players movement across the screen. 
Attack damage will define the damage the enemy will take when a player attacks collides with them.
Defence level will define the level of damage the player will take from enemy attacks.

## **Example**
- **Defence Level**:  Higher defence levels will result in less damage being taken by the player, for example if the player has a defence level of one, attacks that would usually make the player mediumly wounded would result in a minor wound).
 
# **Dependencies**
- [ ] #10 The enemy attacking the player is required for the defence level to have an effect.
  
# **Milestones**
- [ ] Initial Documentation (Aug 21)
- [ ] Unit tests for Attack Damage (Aug 22)
- [ ] Attack Damage Code Implementation (Aug 22)
- [ ] Unit tests for Defence Level (Aug 23)
- [ ] Defence Level Code Implementation (Aug 24)
- [ ] Unit tests for Movement Speed (Aug 25)
- [ ] Movement Speed Code Implementation(Aug 26)
- [ ] Updating Documentation (Aug. 26)
**Completion Deadline:** Aug. 26
 
# **Documentation**
- [Player Statistics](../../wikis/??)
 
# **Member**
- Caitlin Thompson (@tommps) (Caitlin)
