### ISSUE TITLE
Task Team 3: Final boss head design

### ISSUE THREAD

**Issue by quartz-c** [UQdeco2800/2021-studio-6#171]
### Description
Creation of the final boss head graphic for the player to beat the final boss. This boss head is the fish-like head. This will be made using Piskel. User testing will be done after the first creation of the graphic and improved with the advice give.

### Milestones

- [x] -  Create first graphic (24th August)
- [x] -  First user testing (24th August)
- [x] -  Second user testing (26th August)
- [x] - Final Graphic (27th August)

### Documentation

- [x] -  Document User testing
- [x] -  Justify design choice

### Members
Liyang Yu @quartz-c
