### ISSUE TITLE
Safehouse Task: Shopkeeper Design

### ISSUE THREAD

**Issue by tommps** [UQdeco2800/2021-studio-6#172]
# **Description**
**Task:** Shopkeeper design
**Feature:** [#125]
 
In order for the player to be more immersed in the game there needs to be character selling the shop items so that players aren't confused by needing to buy items. This includes both the character standing within the shop that the player can interact with (a more low pixel version similar to the player character, see [Example](https://github.com/UQdeco2800/2021-studio-6/blob/main/source/core/assets/images/Player_Sprite/front01.png)) as well as a character to appear in the buying menu (a higher pixel version similar to those used in the games dialogue boxes, see [Example](https://github.com/UQdeco2800/2021-studio-6/blob/main/source/core/assets/images/dialogue/dialogue.png))

  
# **Milestones**
- [x] Initial Research and References (27/09)
- [x] Design mock ups (30/09)
- [x] User testing of mock ups (2/10)
- [x] Finalised Design (3/10)
- [x] Final Documentation(3/10)
 
**Completion Deadline:** 3/10
  
# **Documentation**
- [Design Shopkeeper](../../2021-studio-6/wiki/Sprint-3-Design:-Shopkeeper)
- [User Testing Shopkeeper: Design](../../2021-studio-6/wiki/Sprint-3:-User-Testing-Shopkeeper:-Design)
 

# **Member**
- Caitlin Thompson (@tommps) (caitlin)
