### ISSUE TITLE
Weapon Task: Weapon Basic Design

### ISSUE THREAD

**Issue by Bluehalomango** [UQdeco2800/2021-studio-6#173]
# **Description**
**Task:** Basic Weapon design
**Feature:** [#139]
 
Basic weapon designs need to be created for the 3 new weapon melee types (Long ranged, short range, medium range). Each new weapon should feel like a logical upgrade to the previous type and should specifically feel more powerful and better than the previous type i.e. the new medium range weapon should feel like an upgrade to the current sword.
  
# **Milestones**
- [ ] Initial Research and References (23/09)
- [ ] Short Ranged Design (24/09)
- [ ] Medium Ranged Design (24/09)
- [ ] Long Ranged Design (24/09)
 
**Completion Deadline:** 24/09
  
# **Documentation**
- TBD
 
# **Member**
- Lucas Bouwman (@Bluehalomango)
