### ISSUE TITLE
Item Task: Weapon Final Design + Feedback

### ISSUE THREAD

**Issue by Bluehalomango** [UQdeco2800/2021-studio-6#174]
# **Description**
**Task:** Final Weapon design
**Feature:** [#139]
 
The three new weapons need to be finalised and undergo user testing to ensure that they fit with the current scope of the game. Mainly, this is to ensure that each new weapon feels a) Related to the weapons previous tier (Sword, Axe and Dagger) b) That it fits into the current setting of the game and c) The appearance of the weapon reflects its purpose (i.e. the new axe should look powerful). Once testing and feedback is recieved, the designs can be finalised and animations can start.
  
# **Milestones**
- [x] Weapon User Testing (26/09)
- [x] Short Ranged Final Design (27/09)
- [x] Medium Ranged Final Design (27/09)
- [x] Long Ranged Final Design (27/09)
 
**Completion Deadline:** 27/09
  
# **Documentation**
- TBD
 
# **Member**
- Lucas Bouwman (@Bluehalomango)
