### ISSUE TITLE
Item Task: Weapon Animations

### ISSUE THREAD

**Issue by Bluehalomango** [UQdeco2800/2021-studio-6#175]
# **Description**
**Task:** Weapon Animations
**Feature:** [#139]
 
Attack animations need to be added to each of the three new weapons after their design is finalised. The animation should ideally reflect the type of attack and should be made in conjuncture with adjusting the stats of the weapon to match properly.
  
# **Milestones**
- [x] Short Ranged Animation (01/10)
- [x] Medium Ranged Animation (02/10)
- [x] Long Ranged Animation (03/10)
 
**Completion Deadline:** 03/10
  
# **Documentation**
- TBD
 
# **Member**
- Lucas Bouwman (@Bluehalomango)
