### ISSUE TITLE
Player Task: Placeholder Player Sprites

### ISSUE THREAD

**Issue by tommps** [UQdeco2800/2021-studio-6#18]
# **Description**
**Task:** Placeholder Player Sprites
**Feature:** Sprint 1 Team 2: Player Feature #8 
 
The placeholder player sprites will be created to be used as initial textures for the player character appearance during early development of the game. These will be later replaced by the finalised sprites. This will include the player facing all four directions and the player while dead. Additionally, modified appearances indicating different damage levels will be included alongside a basic projectile to be utilised in ranged attacking.
  
# **Milestones**
- [x] Creation of four basic directional textures (Aug 21)
- [x] Creation of basic health state textures to be later implemented (Aug 22)
- [x] Basic Projectile texture (Aug 22)
- [x] Inclusion of textures into game files & replacement of default player sprite (Aug 23)
**Completion Deadline:** Aug. 23
 
# **Documentation**
- (placeholder sprites are only for early implementation testing)
 
# **Member**
- Caitlin Thompson (@tommps) (Caitlin)

**Comment by tommps** [comment]
The four directional placeholder sprites.
![LEFT](https://user-images.githubusercontent.com/88131295/130221127-4d138706-d658-466a-978c-75354674fb7e.png)
![RIGHT](https://user-images.githubusercontent.com/88131295/130221131-3f8f9562-11f8-461f-a001-c7c16d8f6433.png)
![FORWARD](https://user-images.githubusercontent.com/88131295/130221132-b1ac0879-3f02-4f65-b268-b5e4fa674ca1.png)
![BACK](https://user-images.githubusercontent.com/88131295/130221133-5e7d39b6-6fdd-45c0-a7ad-a93b0bb0f816.png)

**Comment by tommps** [comment]
The Four Basic Directional Sprites
[4 Basic Directional Sprites.zip](https://github.com/UQdeco2800/2021-studio-6/files/7020923/4.Basic.Directional.Sprites.zip)

**Comment by tommps** [comment]
The Four Directional Sprites in basic versions of three wound states
[4 Directional in Wound States.zip](https://github.com/UQdeco2800/2021-studio-6/files/7020957/4.Directional.in.Wound.States.zip)

**Comment by tommps** [comment]
[Projectile.zip](https://github.com/UQdeco2800/2021-studio-6/files/7024932/Projectile.zip)
