### ISSUE TITLE
Item Task: Unlit Renderer

### ISSUE THREAD

**Issue by Bluehalomango** [UQdeco2800/2021-studio-6#189]
# **Description**
**Task:** Create Unlit Renderer
**Feature:** [#139]
 
After implementing the torch lighting code into the game, it was noticed there was a lighting issue present in the game. As seen in the image below, the player character was incredibly bright on account of being at the centre of the light source. This made it incredibly hard to properly see the character.
![image](https://user-images.githubusercontent.com/88037781/135695592-c07ada77-26d4-4a7d-a7a5-054fe05bdd7c.png)
As such, it was decided to create a new renderer service that is rendered after the lighting so that it is not affected by light sources. This would also solve the issue of the unnecessaryily dark UI elements in the image above.

# **Milestones**
- [x] Create new renderer system in Renderer.java (02/10)
- [x] Add new RenderUnlitService (02/10)
- [x] Change necessary assets to use new unlit renderer (02/10)
 
**Completion Deadline:** 03/10

# **Member**
- Lucas Bouwman (@Bluehalomango)
