### ISSUE TITLE
Enemies Task: Long range enemy

### ISSUE THREAD

**Issue by yourlow** [UQdeco2800/2021-studio-6#19]
# **Description**
**Task:** Long Range Enemy
**Feature:** Enemy #10

Implement a long range enemy, this enemy will fire 'slow' projectiles at the player. If the player is hit by the projectile they will take damage. The enemy will be implemented in the NPCFactory and will be easily spawnable. Research and testing will be done into the implementation of projectiles as well as the scope of projectiles. Placeholder art will be used in this ticket depending on studio decision what happens to this enemy

# **Milestones**
List of steps that need to be completed for this task.
- [x] NPCFactory function for the enemy  (Aug. 19)
- [x] Projectiles spawned in and fired (Aug. 19)
- [x] Projectiles being aimed and shot at the player(Aug. 19)
- [x]  New Physics movement function for bullets 
- [x] Collisions with player
- [x] Despawning bullets on collision with player

 
# **Documentation**
- [Main description of feature](../../wikis/page1)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Name (GitLab Username) (Slack Handle)
- Matthew Holloway @yourlow
