### ISSUE TITLE
Item Task: Torch Animations

### ISSUE THREAD

**Issue by Bluehalomango** [UQdeco2800/2021-studio-6#195]
# **Description**
**Task:** Torch Animations
**Feature:** [#139]
 
To accompany the addition of a torch as a light source ingame, animations should be created to show a flickering torch when the player has it active. These animations should change based on the direction the player is looking in and should stop when the player deactives the torch.
  
# **Milestones**
- [x] Create additional torch sprites to lengthen the animation (02/10)
- [x] Create the animation and the atlas file (03/10)
- [x] Implement the changing animations for each direction (left, right, up and down) and toggling (03/10)
 
**Completion Deadline:** 04/10
 
# **Member**
- Lucas Bouwman (@Bluehalomango)
