### ISSUE TITLE
Task Team 3: Light Beam Design

### ISSUE THREAD

**Issue by jadeomikaela** [UQdeco2800/2021-studio-6#197]
# Description
Creation of a beam of light graphic that will be used in the final boss fight (level 4). This will be used as one of the attacks from the boss. As below, initial designs and user testing will be done to verify the design of the graphic. Animations will also be implemented, but is listed as an extra for this sprint.

# Milestones
- [ ] Initial Design (Wednesday 4th October)
- [ ] User Testing (Wednesday 4th October)
- [ ] Final Design (Thursday 5th October)

# Documentation
- [ ] Document User Testing
- [ ] Justify Design Choices

# Extras 
- [ ] Animations for light beam

#Members
Jade Taylan (@jadeomikaela)
