### ISSUE TITLE
Player Task: Health and Dying

### ISSUE THREAD

**Issue by Bluehalomango** [UQdeco2800/2021-studio-6#20]
# **Description**
**Task:** [Health and Dying](#3).
**Feature:** [#8 ](#2)
 
Modification of the existing health system to a more dynamic and tiered approach. Instead of integer-based health, the player will go through a 'wound' system that reflects their current state, with each worsening state having progressively more health points. As such, additional methods will be added to the pre-existing component to handle both the wound level and level health. Additionally, it will be necessary to implement health regeneration for the specific wound level that the player is on and wound level changes based on specific actions (i.e. getting hit by an enemy, consuming a health potion). 
 
## **Example**
- **Improving Wound State**: The only way for a player to improve their wound state is through some action. At the moment, this is by reaching a checkpoint/safehouse but can include items and abilities when they are introduced.
- **Regeneration**: If a state has 8 hp and the player only takes 2 hp of damage from an enemy, the player can passively regenerate health after a period of time. However, a player can only regenerate hp for their wound level.
- **Damage Cap**: A player can only decrease one wound state at a time. If for instance the player's current state has 2 hp, their next state has 4 hp and takes a 8 hp hit, they will only lose 2 hp and be left in their next state still on 4 hp.
  
# **Milestones**
List of steps that need to be completed for this task.
- [x] Initial Documentation(Aug. 21)
- [x] Wound Level Unit Tests (Aug. 22)
- [x] Wound Level Implementation (Aug. 22)
- [x] Level Health Point Unit Tests (Aug. 23)
- [x] Level Health Point Implementation  (Aug. 23)
- [x] Modify Current isDead function (Aug. 23)
- [x] Health Point Regeneration Unit Tests (Aug. 24)
- [x] Health Point Regeneration Implementation  (Aug. 24)
- [x] Final Documentation(Aug. 24)
 
**Completion Deadline:** Aug. 24
  
# **Documentation**
TBD
 
# **Member**
- Lucas Bouwman (@Bluehalomango)

**Comment by Skybluepanda** [comment]
I'm in the process of designing the health element of the Hud and with this wounds state and health system, do you plan to implement ways for players to increase/decrease values of the maximum health or wounds?

**Comment by Bluehalomango** [comment]
> I'm in the process of designing the health element of the Hud and with this wounds state and health system, do you plan to implement ways for players to increase/decrease values of the maximum health or wounds?

At the moment, the intention that the max number of wound states will remain constant at 3 (Healthy, Wounded, On Death's Door) so you could present that in a more interesting manner than just a number or something for the UI. The state health on the other hand is designed to be able to changed and upgraded at later stages in the game. At the moment, 5 is the current max for state health and that will probably still be the max for this sprint but if you want to think more long term, keep in mind that the max will be able to be increased later on. I already have a method to increase the state health max if you wanted to try and experiment with that but there is not current action to trigger it yet (plans are to implement it in the safehouse upgrading system).

In terms of regeneration, health states regen over time (currently implemented) and wound states are planned to only regen with item pickups (obviously not implemented yet as there are no items). Additionally, the only time max values should decrease is for state health when the player increases their wound state i.e. Wounded has 4 hp but Healthy has 3 hp. 

Hopefully that clears things up a bit, I will be taking another look over the current health documenation to give it an update in the coming days and I'll better specifiy what I said here for that.
