### ISSUE TITLE
Sprint 3 Team 2 Player Task: Torch Design

### ISSUE THREAD

**Issue by SBHATTA19** [UQdeco2800/2021-studio-6#200]
# **Description**
The integration of the lighting feature into the player sprite with the ability to toggle the light on and off to simulate a torch light. 
 
## **Examples**
- **Dark Areas:** Areas that are dimly lit will require the player to activate the torch in order to navigate the map and avoid running into the enemies
- **Buying Torches:** Players will need to purchase a new torch to navigate dim areas once the previous torch runs out. Adds tactical element of using torches effectively, 

# **Dependencies**
- #136 
 
# **Milestones**
- [x] Integrate lighting into the  player sprite(04/10)
- [x] Let the lighting be toggled (05/10)
- [x] Have torch timer with ability to buy new torches (05/10)

# **Documentation**
- [Player Torch](../wiki/Player-Torch)
 
# **Members**
- Sambit Bhattacharya (@SBHATTA19)
