### ISSUE TITLE
Universal Volume Control

### ISSUE THREAD

**Issue by ultimate1112** [UQdeco2800/2021-studio-6#206]
# **Description**
**Task:** #206 
**Feature:** #137 

Sound is very important to the game, but there are situations where the user does not want to hear the game music (ie. in a library or quiet place), or would like the ability to adjust the volume. This ticket deals with implementing a volume control for music and sound effects within the Settings Menu of the game.

# **Dependencies**
None. Possible merge conflicts with tickets relating to implementing additional background music tracks / sound effects.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Implement UI components (Oct. 04)
- [x] Global control of all music elements (Oct. 07)
- [x] Global control of all sound elements (Oct. 07) 
  - Implemented iteratively when sound effects are introduced into the game.
- [x] Documentation update (Oct. 07)

**Completion Deadline:** Oct. 07
 
# **Documentation**
- [Game Engine Documentation: Audio](https://github.com/UQdeco2800/2021-studio-6/wiki/Audio)
 
# **Member**
- Anthony Chiam (@ultimate1112) (ultimate9121#4930)
