### ISSUE TITLE
Enemies Task: Small Enemy

### ISSUE THREAD

**Issue by Hamish-Killen** [UQdeco2800/2021-studio-6#21]
# **Description**
**Task:** Small Enemy
**Feature:** Enemy #10

A enemy will be implemented which is notably smaller than other enemies and the player. This enemy will have a greater speed with lower health and will damage the player when they collide. This is the base implementation of this enemy and will be progressed once the enemy's design and functionality has been finalized through team and studio discussions.

# **Milestones**
List of steps that need to be completed for this task.
- [x] Spawn in new enemy (Aug 19)
- [x] Implement placeholder sprite for new enemy (Aug 19)
- [x] Adjust hitbox to match size (Aug 20)
- [x] Decrease health stat (Aug 20)
- [x] Increase speed (Aug 21)

Extras
- [x] Add animation

 
# **Documentation**
- [Main description of feature](../../wikis/page1)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Hamish Killen @Hamish-Killen
