### ISSUE TITLE
Sprint 4 Team 3: The Final Boss

### ISSUE THREAD

**Issue by Hollycatsoulis** [UQdeco2800/2021-studio-6#210]
# Description
This feature ticket will concentrate on the final boss scene, which is the final level before the player wins the game. this will include ensuring the level can be completed, i.e. the player can kill the boss, enter the sailboat and finish the game. 3 stages will be added to the final boss fight, each with a different enemy or challenge to complete. Testing will be conducted to ensure the level is effective in keeping the user engaged and is highly functional

This feature was worked on last sprint but due to time constraints was not completed. What is currently finished is designs for the dock and boat and the main head design, the boss has phase 1 & 2 partially implemented but not constructed in a way in which the player can transition. there is not way to kill the boss and proceed to the ending

What needs to be completed this sprint. 

Programming wise: 

- There needs to be a 'final boss phase manager' which can manage what the boss can do in each phase, 
- a health bar needs to be implemented, 
- the UI is screwed up because of the static camera 
- stage 1 needs to be fleshed out with more challenge to the player, 
- stage 2 needs some better UX to help the user understand what the player needs to do. 
- stage 3 needs to be fully implemented
- The area itself needs to be designed with assets made for level 3

Design wise: 

- animation or indication of boss firing laser
- laser animation 
- laser sound
- animation or indication of boss taking damage
- boss hurt sound
- tenatacle animations
- tentacle coming out of ground animation
- 2nd stage for the boss head
- health bar outline

# SubFeature/component 

## Phase Manager

The final boss is multi phase and there needs to be some mechanism to transition between phases

## Health bar 

The health bar will help indicated to the player what attacks are doing damage

## Battle 

The player starts in the area with the boss, this is the simple phase to get the player acclimated to the new camera and the area.

the health bar goes down to a certain level and the boss creates spawner enemeis somehow

there will be enemy spawners and the boss firing a laser beam at you, the player has to kill all of the enemy spawners and attack the head a little bit at the end in order to end this phase

-> death scream, screen goes black,  music stops, light goes out, its pitch black,  eyes light up,  the stage is now completely black except for you and the boss and the projectiles coming at you 

turn the lighting engine off screen goes completely black 

 if we get time we will complete this part
the boss fires a lot of bullets at you and tentacles will come out of the ground periodically for the player to avoid and attack 

# Milestones

## Programming
- [x] Boss Phase Manager 10/10
- [ ] UI Fixes 14/10
- [x] Health bar programming 14/10
- [ ] Area Design 14/10

## Design
- [x] animation of boss firing laser 14/10 crystal 
- [x] animation of boss taking damage 14/10 crystal
- [x] laser animation 14/10
- [ ] laser sound 14/10
- [ ] boss hurt sound 14/10
- [x] boss death sound 14/10 crystal
- [ ] health bar outline 14/10
- [x] tentacle design 15/10 holly
- [x] tentacle animation 15/10 holly
- [ ] User testing for various components

# Documentation

# Members
Matthew Holloway @yourlow
Hamish Killen @Hamish-Killen
Niklas Matha @nikmatha
Jade Taylan @jadeomikaela
Holly Catsoulis @Hollycatsoulis
Crystal Yu @quartz-c
