### ISSUE TITLE
Enemies Task: Large Enemy 

### ISSUE THREAD

**Issue by nikmatha** [UQdeco2800/2021-studio-6#22]
### Description

Task: Large Enemy 
Feature: Enemy #10 

This enemy will be notably larger than the other enemies being implemented. As such, it will be slower but do more damage to the player and there will also be a larger hitbox. Furthermore, this enemy will have more health compared to the other enemies. 

### Milestones

- [x] Add enemy into NPCFactory (Aug 20)
- [x] Allow the enemy to be spawned easily
- [x] Implement placeholder sprite (Aug 20)
- [x] Adjust hitbox (larger) (Aug 20)
- [x] Change the speed of the enemy to be slower (Aug 23)
- [x] Increase the damage (Aug 23)

### Members 
Niklas Matha (@nikmatha)
