### ISSUE TITLE
Team 2 Extra Task: Sound Effects

### ISSUE THREAD

**Issue by ultimate1112** [UQdeco2800/2021-studio-6#222]
# **Description**
**Task:** #222. (Continuation of #137).
**Feature:** #223.

Adding more sound effects to the game. The aim is to immerse the player into the game, so the sound effects must enrich the user experience and be cohesive with the art style / game theme.

> For sound effects, we will now also source from royalty-free sound effect libraries.
This issue was discussed with @HannahHinckfuss, progress will focus on the effective use of integration of the sound effects (ie. documentation and user testing).

# **Dependencies**
- #206.
 
# **Milestones**
- [x] Brainstorm / Initial Design Decisions + Reasoning (Oct. 14)
- [x] Acquire assets (Oct. 16)
- [x] Formal User Testing (Oct. 20)
- [x] Finalize Documentation (Oct. 20)
 
**Completion Deadline:** Oct. 20
 
# **Documentation**
- [Sprint 3 Documentation](../wiki/Sprint-3:-Player-Sound-Effects)
- [Sprint 4 Documentation](../wiki/Sprint-4:-Player-Sound-Effects)
 
# **Member**
- Anthony Chiam (@ultimate1112) (ultimate9121#4930)
