### ISSUE TITLE
Team 2 Polishing Task: User Testing, Combat & Item Balancing

### ISSUE THREAD

**Issue by tommps** [UQdeco2800/2021-studio-6#225]
# **Description**
**Task:** User Testing, Combat & Item Balancing
**Feature:** #212
 
Completion of user tests in order to balance all elements to ensure the player experiences the game at the correct difficulty in order to reach the established emotional goals of the game (i.e. not too easy so users do not feel enough tension and not difficult enough that it frustrates the user rather than being challenging). This includes balancing the items the player has access to (including the strength of weapons) alongside the damage dealt by the different enemy types.
   
# **Milestones**
- [ ] Writing up a testing plan (13/10)
- [ ] Performing test plan on users (16/10)
- [ ] Evaluating and Modifying in response (17/10)
- [ ] [Optional] Modify/write new testing plan to fit changes (17/10)
- [ ] Reperform the testing plan on users (20/10)
- [ ] Evaluating and performing final changes (20/10)

**Completion Deadline:** 20/10
 
# **Documentation**
- [User Testing: Balancing Combat & Items](../../User-Testing:-Balancing-Combat-&-Items)
 
# **Member**
- Caitlin Thompson (@tommps) (Caitlin)
