### ISSUE TITLE
Team 2 Polishing Task: Level Layout Updates

### ISSUE THREAD

**Issue by tommps** [UQdeco2800/2021-studio-6#226]
# **Description**
**Task:** Level Layout Updates
**Feature:** [#212 ]
 
As an improvement to the game some adjustments will be made to the current layout of the game. The main purpose of this is to immerse the player more by either adding more complexity or making the layout less 'game like'.

This includes removing the linearity of the first level (allowing the player to get more used to moving around and immersing the player more by giving them more to do) and altering all current levels to ensure the 'void' space on the edge of all the levels in order to increase player immersion and implying a much larger world, pseudo lengthening their journey.
  
# **Milestones**
- [x] Initial mock ups/sketches of new Level 1 layout (12/10)
- [x] Implementation of final Level 1 Layout (14/10)
- [x] Allocating enemy, item and light positions (16/10)
- [x] Final Documentation
# **Extra**
- [ ] Removing void space at edge of Levels 2/3 (16/10)
 
**Completion Deadline:** 16/10
  
# **Documentation**
- [Sprint 4: Level 1 Layout](../../2021-studio-6/wiki/Sprint-4:-Level-1-Layout)
 
# **Member**
- Caitlin Thompson (@tommps) (caitlin)

**Comment by tommps** [comment]
Due to needing to take on the assigning positions that was originally another teams job (from the studio), the removing void space was pushed back from this ticket as more of an extra than part of the task

**Comment by tommps** [comment]
finished without completing the extra void removals
