### ISSUE TITLE
Team 2 Polishing Task: Polishing Shop

### ISSUE THREAD

**Issue by 25Ericcheong** [UQdeco2800/2021-studio-6#227]
Feature: #212 

# **Description**
Shop is mostly completed now. These are miscellaneous tasks that are required to make room for the completion of an additional task for grenade and finalizing feedback being returned to user and etc (will be shown in milestones)

# **Dependencies**
- #228 Once this ability is completed - changing ability to grenade can be seen when player decides to purchase grenade ability in shop
 
# **Milestones**
- [x] Update button feedback to have an additional feedback called "Insufficient Funds" when player has no funds to make a purchase on selected item (13/10)
- [x] Player image should be updated when an armor/helmet (or both is equipped) in the shop UI (14/10)
- [x] Torch should be replaced with fuel sprite - this should also update/add torch timer (increases time it takes for torch to run out when item is purchased in shop) (16/10)
- [x] Bandage removal from shop UI and have it spawned in safehouse instead. In addition to that, this item image button will be replaced with grenade ability for player to purchase (this will also include updating the buying system for when this ability is bought) (17/10)
- [x] Documentation (18/10)
- [x] Functional testing (18/10)

# **Documentation**
- [Abilities update](https://github.com/UQdeco2800/2021-studio-6/wiki/Sprint-4-Player-Abilities)
- [Safehouse overview update](https://github.com/UQdeco2800/2021-studio-6/wiki/Sprint-4:-Safehouse-Overview)
 
# **Members**
- Eric Cheong Kai Kit (@25Ericcheong) (Eric)
