### ISSUE TITLE
Team 2 Polishing Task: Individual Balancing

### ISSUE THREAD

**Issue by Bluehalomango** [UQdeco2800/2021-studio-6#229]
# **Description**
**Task:** Balancing weapons, items and enemies
**Feature:** [#212 ]
 
As difficulty is a fundamental factor in player experience, it is imperative to ensure a proper and fair balance between challenge and fun. As the development of the game has progressed, new items, enemies and weapons have progressively been added in with minimal attention given to integrating their individual stat values (i.e. damage, health, etc.) with the existing values. 

This is much more noticeable when considering the divide between player and enemy related values, as each feature was developed independently from each other. As such, it is now necessary to unify the balancing scope of the two previously disparate elements to create a cohesive and complete experience for the user. Ideally, the game should be able to apeal to a range of player's with varying skill levels. With this in mind, this overhaul will require significant user feedback to optimally balance the values.

# **Milestones**
- [ ] Initial balancing overhaul (12/10)
- [ ] First batch of user tests (15/10)
- [ ] Balance Adjustments (17/10)
- [ ] Final user testing  (18/10)
- [ ] Final Adjustments (19/10)
- [ ] Documentation (20/10)
 
**Completion Deadline:** 20/10
  
# **Documentation**
- TBD
 
# **Member**
- Lucas Bouwman (@Bluehalomango)

**Comment by Bluehalomango** [comment]
Closed due to duplication and task merging.
