### ISSUE TITLE
Player Task: Attacks

### ISSUE THREAD

**Issue by SBHATTA19** [UQdeco2800/2021-studio-6#23]
# **Description**
**Task:**  [Attacks](#23 )
**Feature:** #8 

Implement the attack feature for the game that defines the interaction between the enemies and the player in regards to the damage dealt by each party. The player will be interacting with the enemy throughout the game and may damage the enemy through attacks. Alternately, prolonged sustained attacks by the enemy should trigger the loose condition of the player. A variety of different weapons will need to be considered in the context of attacks within the game.
 
## **Examples**
- **Weapons**: Depending on the level, there will be various weapons and tools available to the player enabling them to conduct a particular set of attacks. These weapons will progress over time.
- **Attack Damage**: As players progress through the game, the damage model of the player and the amount of damage inflicted will have to scale. 

# **Dependencies**
- [ ] #10 in order to understand the enemy types and required damage criteria as well as testing the weapons
- [ ]  #7 in order to understand the required rate of progression of the melee weapon to retain playability with increased difficulty. 
 
# **Milestones**
List of steps that need to be completed for this task.

- [ ] Establish solid conceptual understanding of the types of weapon and combat styles to be considered in the game (Aug. 20)
- [ ] Develop pseudocode to represent the interaction between the player and enemies (Aug. 21)
- [ ] Develop initial melee weapon and integrate into game (Aug. 23)
- [ ] Devise weapon progression considering enemy development (Aug. 24)
- [ ] Integrate weapon progression system and damage model into game  (Aug. 27)
- [ ] Test and improve functionality of the weapon system using enemies (Aug. 28)
 
**Completion Deadline:** Aug. 28

 
# **Documentation**
- ...
 
# **Member**
- (@SBHATTA19 ) (Sambit Bhattacharya)

**Comment by 25Ericcheong** [comment]
Combined with #36
