### ISSUE TITLE
Team 2 Polishing Task: Update Rock Throwable

### ISSUE THREAD

**Issue by Bluehalomango** [UQdeco2800/2021-studio-6#231]
# **Description**
**Task:** Update Rock Asset
**Feature:** [#223]
 
When the rock was first added as a ranged, limited-use weapon in a previous sprint, it was intended that there would be a separate asset for the rock asset that you pick up and the rock that you throw. Due to time constraints at that time, this was revised to just a single asset for both cases. Since the game has entered polishing, and due to feedback on inconsistency and lack of visual feedback from the ranged attack, it has been deemed worthwhile to revist the ranged attack assets. 

Specifically, a new sprite will be created, as originally envisioned, to distinguish the pick-up and thrown assets. Additionally, a new animation of the rock breaking will be created to give visual feedback for when the rock hits a target or obstacle.

# **Milestones**
- [x] New thrown rock asset (12/10)
- [x] Rock breaking animation (13/10)
- [x] Animation integration into code (14/10)
- [x] Documentation (16/10)
 
**Completion Deadline:** 16/10
  
# **Documentation**
- [Polishing Player Assets] (https://github.com/UQdeco2800/2021-studio-6/wiki/Sprint-4:-Polishing-Player-Assets)
 
# **Member**
- Lucas Bouwman (@Bluehalomango)
