### ISSUE TITLE
Firefly Bug NPC

### ISSUE THREAD

**Issue by kainphoton** [UQdeco2800/2021-studio-6#233]
# **Description**
**Task:** Firefly Bug NPC
**Feature:**  Lighting Assets (#241)

Implement a firefly bug NPC that moves around in Level 2 and 3.  The NPC can act as a light source for the player to see parts of the level and also help the player fight around the enemy in case the player's torch runs out.  The firefly is not interactable and will wander around randomly around its proximity.  
 
# **Milestones**
- [x] Firefly asset (a dot) (Oct. 12)
- [x] Add firefly entity to NPCFactory (Oct.16)
- [x] Add lighting source component to the firefly entity (Oct. 16)
- [x] Spawn fireflies entities in level 2 and 3 (Oct. 16)
- [x] Add AITaskComponent inside firefly entity creator function in NPCFactory  (Oct. 19)
- [x] Documentation for firefly bug NPC

**Completion Deadline:** Oct. 19

# **Documentation**
- [Sprint 4: FireFlies Bug NPC](../wiki/Sprint-4:-Fireflies-Bug-NPC)
 
# **Member**
- Hai (@kainphoton)
