### ISSUE TITLE
Darkness (22nd Oct)

### ISSUE THREAD

**Issue by DancingBrian** [UQdeco2800/2021-studio-6#248]
# **Description**
**Task: Darkness** 
**Feature: #217 Enemies: Darkness, Reactions, and AI**

The lighting engine currently provides ambient lighting and atmosphere that is purely cosmetic. This aims to attach functionality to the lighting and allow other components to act based on the current lighting conditions.

This feature will make users want to stay in the light which:
- Ties into the current story
- Add more interesting gameplay
- Adds a reason for the player to purchase the torch item.
If there is enough time, further cosmetic changes to the lighting engine using shaders could be implemented to further enhance the player experience.

## Detect light level
A component to notify if an entity is within a light source or not.

## Decrease visibility
Adjust lighting settings to have a moodier feeling.

## Allow way to ignore dynamic lights
Create lighting layers that allows some sprites to ignore the dynamic lighting.

# **Dependencies**
No dependencies for this task

# **Milestones**
- [x] Create the darkness detection component (Finished 10/10)
- [x] Add light layers to separate sprites to be lit and unlit (Already implemented)
- [x] Change default ambient lights (15/10)
- [x] Create documentation (15/10)
- [x] Create unit tests (15/10)
- [x] Finalise documentation (22/10)

**Completion Deadline:** 22nd Oct

# **Extras**
- [x] Custom shaders

# **Documentation**
[Sprint 4: Darkness](https://github.com/UQdeco2800/2021-studio-6/wiki/Sprint-4:-Darkness)

# **Member**
- Joseph (@implex001) (implex001#2331)
