### ISSUE TITLE
AI programming (21st Oct)

### ISSUE THREAD

**Issue by DancingBrian** [UQdeco2800/2021-studio-6#249]
# **Description**
**Task: AI Programming** 
**Feature: #217 Enemies: Darkness, Reactions, and AI**

Refine the AI used by enemies (a.k.a. Shadow Crawlers) to decide how they move and attack. Because the story describes Shadow Crawlers as creatures that thrive in the darkness, this task will attempt to make them more aggressive if the lighting level at the enemy’s position is low. This will result in a game that is more challenging and heightens the player’s sense that they need to stay in the light.

## Increase activation range if player in dark
The current version of the game activates enemies when the player is within a fixed range. The player is then chased and/or shot at. By increasing the activation range of enemies when it is dark, the lighting mechanic is no longer purely cosmetic and adds another dimension to gameplay.

## More aggressive enemies in the dark
Once the enemies are activated, they move and/or shoot faster depending on the lighting level at their position.

## Shoot projectiles towards predicted player position
The current enemies either shoot projectiles in fixed directions (*Short Range Enemy*) or towards the player’s position (*Long Range Enemy*). However, these projectiles are easy to dodge. We can increase the game’s difficulty by predicting where the player will be depending on their movement and firing a projectile to meet the player at that point.

# **Dependencies**
- [x] Darkness #248 (for *activation range* and *aggressive enemies*)

# **Milestones**
- [x] Create documentation (11th Oct)
- [x] Determine whether the enemy is in light/dark (12th Oct)
- [x] Determine whether the player is in light/dark (12th Oct)
- [x] Adjust AI component to make enemy faster in the dark (12th Oct)
- [x] Adjust AI component to make enemy shoot faster in the dark (15th Oct)
- [x] Increase enemy activation range when player in the dark (15th Oct)
- [x] Create unit tests (18th Oct)
- [x] Finalise documentation (21st Oct)

**Completion Deadline:** 21st Oct

# **Extras**
- [ ] Adjust shooting projectile AI to focus on player expected position
- [ ] Review the current AI `WanderingTask`

# **Documentation**
[Sprint 4: Enemy AI and Interactions](https://github.com/UQdeco2800/2021-studio-6/wiki/Sprint-4:-Enemy-AI-and-Interactions)

# **Member**
- Brian Stewart (@DancingBrian) (Brian#8636)
- Renée (@NightingaleUQ) (Renée)
