### ISSUE TITLE
Enemies Task: Large Enemy Design

### ISSUE THREAD

**Issue by jadeomikaela** [UQdeco2800/2021-studio-6#25]
### Description

This enemy sprite will be larger than the other enemies. The design of the enemies will use dark colours in order to match the dark theme of the game. Graphics for enemy movement and attacks will be added as a milestone to decide how they may attack based on their design.

### Milestones

- [x] Create basic enemy sprite (Aug 24th)
- [x] Make it pixelated (Aug 24th) 
- [x] Come up with attacks for enemies based on design (Aug 25th)

### Extras

- [x] Create basic movement and attack graphics
- [x] Create animation

### Members

Jade Taylan (@jadeomikaela)

**Comment by jadeomikaela** [comment]
'coming up with attacks for enemies based on design' will be talked about in the group meeting on tuesday 24th, and then finalised on the 25th.

**Comment by jadeomikaela** [comment]
This ticket (and very possibly the other enemy designs too) may need to be pushed back till friday (3rd sep). A test animation for this sprite is being handed to the programmers by tomorrow, and will be tested for flaws. 

once all flaws are out of the way, the rest of the animations will be done.

**Comment by jadeomikaela** [comment]
Correction - animations are an extra for this sprint
