### ISSUE TITLE
Enemy Reactions (21st Oct)

### ISSUE THREAD

**Issue by SpiritBlues7** [UQdeco2800/2021-studio-6#250]
# **Description**
**Task: Enemy Reactions** 
**Feature: #217 Enemies: Darkness, Reactions, and AI**

We will add multiple enemy reactions to:
- Create a more "Juicy" game, i.e. more responsive to the players actions and environment.
- Give feedback to the player, e.g. enemy flashes red when hit
- Add to the horror themes, e.g. displaying glowing eyes when enemy in darkness.

The following enemy reactions will be added to the game:
- Visual and audible feedback when the enemy is hit
- Visual feedback when the enemy is critically wounded
- Visual feedback when the enemy is in darkness
- Visual and audible feedback when the enemy is dead
- Audible feedback if enemy is near player
- Audible feedback when the enemy attacks/shoots
- Audible feedback when an enemy is spawned from a spawner

# **Dependencies**
- [x] Enemy Sound Effects #253 
- [x] Glowing Eyes Component #251 
- [x] Darkness #248

# **Milestones**
- [x] Create documentation
- [x] Create a generic dead body (most likely a pool of blood) (15th Oct)
- [x] Sprite change on enemy being hit (15th Oct)
- [x] Sprite change on enemy low health (15th Oct)
- [x] Activate glowing eyes render component on enemy in darkness (16th Oct)
- [x] Sound effect play on enemy hurt (17th Oct)
- [x] Sound effect play on enemy dead (17th Oct)
- [x] Sound effect play if enemy detects the player (17th Oct)
- [x] Sound effect play when enemy attacks/shoots (17th Oct)
- [x] Sound effect plays when enemy spawns from a spawner (17th Oct)
- [x] Create Unit Tests (19th Oct)
- [x] Finalise Documentation (21st Oct)

**Completion Deadline:** Oct 21st

# **Extras**
- [x] Enemies have a chance to drop loot when killed (18th Oct)
- [x] Change sprite to enemy dead sprite when enemy dies (18th Oct)
- [ ] Fade transition between different sprites
- [x] Enemy knockback

# **Documentation**
[Sprint 4: Enemy AI and Interactions](https://github.com/UQdeco2800/2021-studio-6/wiki/Sprint-4:-Enemy-AI-and-Interactions)
[Sprint 4: Enemy Loot](https://github.com/UQdeco2800/2021-studio-6/wiki/Sprint-4:-Enemy-Loot)

# **Member**
- Brian Stewart (@DancingBrian) (Brian#8636)

**Comment by DancingBrian** [comment]
Hey @Bluehalomango, we were thinking of giving enemies a chance to drop items when killed (particular the larger harder enemies). Are there particular items you would prefer them to drop (or not drop)?
