### ISSUE TITLE
Glowing eyes component (Oct 15th)

### ISSUE THREAD

**Issue by DancingBrian** [UQdeco2800/2021-studio-6#251]
# **Description**
**Task: Glowing Red Eyes Component** 
**Feature: #217 Enemies: Darkness, Reactions, and AI**

When the enemy is in darkness their eyes will still be visible. This will both let the user know where the enemies are and also create an uneasy feeling seeing enemies "watching" them.

We will create the glowing eyes as a separate render component that contains just the eyes. 

# **Dependencies**
No dependencies

# **Milestones**
- [x] Create documentation (11th Oct)
- [x] Create new render component that loads the enemy eyes sprite (12th Oct)
- [x] Position enemy eye sprite correctly on enemy (12th Oct)
- [x] Add the render component to each enemy (12th Oct)
- [x] Create unit tests (15th Oct)
- [x] Finalise documentation (15th Oct)

**Completion Deadline:** Oct 15th

# **Extras**
No extra tasks

# **Documentation**
[Sprint 4: Enemy AI and Interactions](https://github.com/UQdeco2800/2021-studio-6/wiki/Sprint-4:-Enemy-AI-and-Interactions)

# **Member**
- Brian Stewart (@DancingBrian) (Brian#8636)
