### ISSUE TITLE
Enemy hitbox

### ISSUE THREAD

**Issue by DancingBrian** [UQdeco2800/2021-studio-6#252]
# **Description**
**Task: Enemy Hitboxes** 
**Feature: #217 Enemies: Darkness, Reactions, and AI**

We would like to adjust the enemy hitboxes to more accurately represent where the enemy/projectile is and whether the enemy/projectile can hit the player.

Adjusting the hitboxes of the enemies will reduce frustration of the player so they aren't confused why they can't get past an enemy or why they were just hit by an enemy.

# **Dependencies**
No dependencies for this task

# **Milestones**
- [x] Large enemy - Physical Hitbox
- [x] Large enemy - Attack Radius
- [x] Long Range Enemy - Physical Hitbox
- [x] Small Enemy - Physical Hitbox
- [x] Small Enemy - Attack Radius
- [x] Spawner Enemy - Physical Hitbox
- [x] Tough Ranged Enemy - Physical Hitbox

# **Extras**
No extras for this task

# **Documentation**
[Coming soon]

# **Member**
- Brian Stewart (@DancingBrian) (Brian#8636)
- Joseph (@implex001) (implex001#2331)
