### ISSUE TITLE
Enemy sound effects (19 Oct)

### ISSUE THREAD

**Issue by DancingBrian** [UQdeco2800/2021-studio-6#253]
# **Description**
**Task: Enemy Sound Effects** 
**Feature: #217 Enemies: Darkness, Reactions, and AI**

The game currently sounds very quiet with only music providing any source of sound. Here, we add sound effects that play when the enemy changes state.

These states are defined as follows:
- Detection sound: The player moves within range of the enemy and is now being attacked
- Attack sound: The enemy performs a melee attack against the player
- Shoot sound: The enemy fires a projectile
- Spawn enemy sound: An enemy is spawned
- Hurt sound: The enemy takes damage from the player
- Death sound: The enemy runs out of health and ‘dies’

# **Dependencies**
No dependencies for this task.

# **Milestones**
- [x] Large enemy: detection sound (16 Oct)
- [x] Large enemy: attack sound (16 Oct)
- [x] Large enemy: hurt sound (16 Oct)
- [x] Large enemy: death sound (16 Oct)
- [x] Long Range Enemy: shoot sound (16 Oct)
- [x] Long Range Enemy: death sound (16 Oct)
- [x] Small Enemy: detection sound (16 Oct)
- [x] Small Enemy: attack sound (16 Oct)
- [x] Small Enemy: death sound (16 Oct)
- [x] Spawner Enemy: Spawn enemy sound (16 Oct)
- [x] Spawner Enemy: hurt sound (16 Oct)
- [x] Spawner Enemy: death sound (16 Oct)
- [x] Tough Ranged Enemy: shoot sound (16 Oct)
- [x] Tough Ranged Enemy: hurt sound (16 Oct)
- [x] Tough Ranged Enemy: death sound (16 Oct)
- [x] Sound levels balancing across all enemies (16 Oct)
- [x] User testing (17 Oct)
- [x] Create Documentation (17 Oct)
- [x] Finalise Documentation (19 Oct)

**Completion Deadline**: Tue 19 Oct

# **Extras**
No extras for this task ticket

# **Documentation**
[Sprint 4: Enemy Sound Effects](https://github.com/UQdeco2800/2021-studio-6/wiki/Sprint-4:-Enemy-Sound-Effects)

# **Member**
- Renée (@NightingaleUQ) (Renée)
- Brian Stewart (@DancingBrian) (Brian#8636)
