### ISSUE TITLE
Large Enemy (Oct 20th)

### ISSUE THREAD

**Issue by DancingBrian** [UQdeco2800/2021-studio-6#254]
# **Description**
**Task: Large Enemy** 
**Feature: #217 Enemies: Darkness, Reactions, and AI**
Currently the Large enemy is designed to be static, with no reaction components. The task will make the Large enemy change when encountered damage and when in darkness.

Flashing the enemy red on every hit and having it bleed when on low health is a good indicator for damage.

When in darkness, the sprite would have red glowing eyes. 

# **Dependencies**
No current dependencies.

# **Milestones**
- [x] Create Documentation (11/10)
- [x] Redesign Plan (15/10)
- [x] Sprite when enemy is hit (17/10)
- [x] Additional Movement direction sprites (17/10)
- [x] Low Health Sprite (17/10)
- [x] Low Health Move Sprite (17/10)
- [x] Low Health when enemy is hit Sprite (17/10)
- [x] Glowing Eye Layer Sprite (17/10)
- [x] Glowing Eye Layer Movement Sprites (17/10)
- [x] User Testing (18/10)
- [x] Finalise Documentation (20/10)

**Completion Deadline :** 20th October

# **Extras**
- [x] Polish current sprite
- [ ] Attack animations
- [x] Dead Sprite

# **Documentation**
Old Documentation: [Large Enemy](https://github.com/UQdeco2800/2021-studio-6/wiki/Large-Enemy)
New Documentation:  [Sprint 4: Large Enemy](https://github.com/UQdeco2800/2021-studio-6/wiki/Sprint-4:-Large-Enemy)

# **Member**
- Suhas (@suhasudupaa) (Huxley#5371)
