### ISSUE TITLE
Long Range Enemy (Oct 20th)

### ISSUE THREAD

**Issue by DancingBrian** [UQdeco2800/2021-studio-6#255]
# **Description**
**Task: Long Range Enemy** 
**Feature: #217 Enemies: Darkness, Reactions, and AI**
Currently the Long Range Enemy is designed to be static, with no reaction components. This task will make the long range enemy change when encountering damage and when in darkness. 

Flashing the enemy red on every hit and having it bleed when on low health is a good indicator for damage.

When in darkness, the sprite would have red glowing eyes. 

# **Dependencies**
No Current Dependencies.

# **Milestones**
- [x] Create Documentation (11/10)
- [x] Redesign Plan (17/10)
- [x] Additional Movement direction sprites (17/10)
- [x] Glowing Eye Layer Sprite (17/10)
- [x] Glowing Eye Layer Movement Sprites (18/10)
- [x] User Testing (18/10)
- [x] Finalise Documentation (20/10)

**Completion Deadline:** 20th October

# **Extras**
- [x] Polish current sprite
- [ ] Attack animations
- [x] Dead Sprite

# **Documentation**
Old Documentation: [Long Range Enemy](https://github.com/UQdeco2800/2021-studio-6/wiki/Long-Range-Enemy)
New Documentation: [Sprint 4: Long Range Enemy](https://github.com/UQdeco2800/2021-studio-6/wiki/Sprint-4:-Long-Range-Enemy)

# **Member**
- Suhas (@suhasudupaa) (Huxley#5371)
