### ISSUE TITLE
Tough Ranged Enemy (18th Oct)

### ISSUE THREAD

**Issue by DancingBrian** [UQdeco2800/2021-studio-6#258]
# **Description**
**Task: Tough Ranged Enemy** 
**Feature: #217 Enemies: Darkness, Reactions, and AI**
Tough Ranged Enemy is rare and the biggest challenge the player can face individually before the boss. It’ll have a large amount of health and move slowly, and fire projectiles at the player at set intervals. To reward the player for the challenge, this enemy will drop a greater reward.

Optional AI: The Tough Ranged Enemy will have attack phase and rest phase. After detecting the player, it’ll go into the attack phase and continuously fire at the player for x seconds. Then it’ll enter a rest phase where it’ll be stationary and inactive. After a set amount it’ll reenter the attack phase with some warning sounds. (Extra optional, enters attack phase when low on health as extra challenge).

# **Dependencies**
No dependencies for this task

# **Milestones**
- [x] Create Documentation (11/10)
- [x] Idle Sprite (17/10)
- [x] Moving Sprite (17/10)
- [x] Hit Sprite (17/10)
- [x] Low Health Sprite (17/10)
- [x] Low Health Move Sprite (17/10)
- [x] Low Health Hit Sprite (17/10)
- [x] Glowing Eye Layer Sprite (17/10)
- Attack Animation (17/10) (truncated)
- [x] Finalise Documentation (17/10)
- [x] User Testing (18/10)

**Completion Deadline:** 18th Oct

# **Extras**
- [x] Dead Sprite

# **Documentation**
Old Documentation: [Tough Long Range Enemy](https://github.com/UQdeco2800/2021-studio-6/wiki/Tough-Long-Range-Enemy)
New Documentation: [Sprint 4: Tough Long Range Enemy](https://github.com/UQdeco2800/2021-studio-6/wiki/Sprint-4:-Tough-Long-Range-Enemy)

# **Member**
Chris (@Skybluepanda)(Bluepanda#5218)
