### ISSUE TITLE
Enemies Task: Short-Range Enemy Design

### ISSUE THREAD

**Issue by jadeomikaela** [UQdeco2800/2021-studio-6#26]
### Description

This enemy will take on a default enemy design - these will be medium sized enemies with mediocre short range abilities and damage. Like the other enemy sprites, they will also take on dark colours to fit the theme of this game. 

### Milestones

- [x]  Create basic enemy sprite (Aug 24th)
- [x] Come up with attacks for enemies based on design (Aug 25th)
- [x] Create basic movement and attack graphics (Aug 29th)

### Members 
Crystal Yu (@quartz-c)
