### ISSUE TITLE
Team 2 Poslishing Task: Environmental Assets Design

### ISSUE THREAD

**Issue by ydiannaj** [UQdeco2800/2021-studio-6#267]
# **Description**
**Task:** [Team 2 Poslishing Task: Environmental Assets Design] (#267 )
**Feature:** [Sprint 4 Team 2: Asset Polishing](#223 )

## **Insperations**
![pngwing com](https://user-images.githubusercontent.com/62837203/137418521-1f5d438c-0e58-4dcc-9c0f-7393ceca83b3.png)

# **Milestones**
List of steps that need to be completed for this task.
- [x] 2 twigs variations (Oct. 16)
- [x] 2 bush variations (Oct. 16)
- [x] 2 log variations (Oct. 16)
- [x] 2 tree variations (one animated) (Oct. 16)
- [x] 6 path variations (Oct. 16)
- [x] 3 dirt patch variations (Oct. 17)
- [x] stump (Oct. 17)
- [x] rubble (Oct. 17)
- [x] Animated extinguished campfire (Oct. 18)
- [x] Fallen down tree (Oct. 18)
- [x] Documenation (Oct. 20)
 
**Completion Deadline:** Oct. 20

# **Documentation**
- [Polishing Environment Assets] (https://github.com/UQdeco2800/2021-studio-6/wiki/Sprint-4:-Polishing-Environment-Assests)

# **References**
https://www.pngwing.com/en/free-png-vhpyo/download

# **Member**
- Jing Yang (@ydiannaj)
