### ISSUE TITLE
Team 2 Polishing Task: Realistic Torchlight

### ISSUE THREAD

**Issue by Bluehalomango** [UQdeco2800/2021-studio-6#269]
# **Description**
**Task:** Realistic Torchlight
**Feature:** [#212]
 
In order to create a more realistic and immersive experience, a new realistic lighting component should be implemented. This component should attempt to recreate a natural flickering light, akin to a campfire or candlelight. This component can then be used to replace specific existing light components to create a more polished and juicy environment. Specifically, it can be used for the player light sources (torch and firecracker) to help distinguish them from the environment.

# **Milestones**
- [x] Create new FlickerLightComponent (14/10)
- [x] Add FlickerLightComponent to player torch (15/10)
- [x] Add FlickerLightComponent to player firecracker (16/10)
- [x] Documentation (18/10)
 
**Completion Deadline:** 18/10
  
# **Documentation**
- [Sprint 4 FlickerLightComponent](../wiki/Sprint-4---FlickerLightComponent)
 
# **Member**
- Lucas Bouwman (@Bluehalomango)
