### ISSUE TITLE
Player Task: Appearance 

### ISSUE THREAD

**Issue by ydiannaj** [UQdeco2800/2021-studio-6#27]
# **Description**
**Task:** [Appearance (30 August)](#27 ).
**Feature:** [Player](#2)

A detailed player appearance will be generated, including gesture, pose, facial expressions, weapon, and armour. This is a design base task, so the player spirit is not yet integrated with the code. However, the design will coordinate with the dim theme. To stimulate players’ feelings of tension, the sprite will be designed to be emaciated.

## **Example**
- **Facial Expression**: Different facial expressions for different stats or actions
- **Gesture and Pose**: Different gestures and poses for different stats or actions, such as running, stand, squatting and dying
![pixel_gems_by_mokkaquill_dah7sgl-fullview](https://user-images.githubusercontent.com/62837203/130158356-b4ea6db8-d890-47d6-8e0c-f3bbb8aed5cd.jpg)
![Free-Villagers-Sprite-Sheets-Pixel-Art5-720x480](https://user-images.githubusercontent.com/62837203/130161199-a244fad4-0d8f-4c21-bfc3-c287c4101cab.jpg)
![Free-3-Character-Sprite-Sheets-Pixel-Art5-720x480](https://user-images.githubusercontent.com/62837203/130161282-00c095dc-c929-453b-ab51-bb456bf0db5f.jpg)

# **Dependencies**
- [x] Player Task: Long Ranged and Melee Attacks #36 
- [x] Player Task: Dashing #41 

# **Milestones**
List of steps that need to be completed for this task.
- [x] Completed gesture and poses (Aug. 23)
- [x] Armour and weapon (Aug. 26)
- [x] Facial expressions (Aug. 28)
- [x] Colour and complete (Aug. 30)
 
**Completion Deadline:** Aug. 30

# **References**
https://www.deviantart.com/mokkaquill/art/Pixel-Gems-633578709
https://craftpix.net/freebies/free-villagers-sprite-sheets-pixel-art/
https://craftpix.net/freebies/free-3-character-sprite-sheets-pixel-art/

# **Member**
- Jing (@ydiannaj) (Jing Yang)

**Comment by jadeomikaela** [comment]
Looking good there! Just wondering for enemy animations later on, how many frames per second will we be doing? I will also be communicating with other teams and commenting on other tickets about this :)
