### ISSUE TITLE
Enemies Task: Small enemy design

### ISSUE THREAD

**Issue by quartz-c** [UQdeco2800/2021-studio-6#28]
### Description
This enemy will take on a default enemy design - these will be small sized enemies with fast attacking speed and damage. 

### Milestones

- [x]  Create basic enemy placeholder (Aug 19th)
- [x]  Come up with attacks for enemies based on design (Aug 19th)
- [x]  Create basic movement and attack graphics (Aug 22th)
- [x]  Convert to animations (Aug 25th)

### Members
Liyang Yu (@quartz-c)
