### ISSUE TITLE
Enemies Task: Long-range attack

### ISSUE THREAD

**Issue by quartz-c** [UQdeco2800/2021-studio-6#29]
### Description
This enemy will take on a default enemy design - these will be enemies with slow speed but long range attack and high damage. Like the other enemy sprites, they will also take on dark colours to fit the theme of this game.

### Milestones

- [x] Create basic enemy sprite (Aug 24th)
- [x] Make it pixelated (Aug 24th)  
- [x] Come up with attacks for enemies based on design (Aug 25th)

### Extras

- [x]  Create basic movement and attack graphics 
- [x]  Convert to animations 

### Members
Jade Taylan (@jadeomikaela )
