### ISSUE TITLE
Player Task: Long Range Attacks

### ISSUE THREAD

**Issue by 25Ericcheong** [UQdeco2800/2021-studio-6#30]
# **Description**
**Task:** [Long Range Attacks](#30 ).
**Feature:** #5 
 
Apart from the ability for player to melee an enemy, an additional way of attacking an enemy will also be implemented. This is a ranged type attack. This will allow players to throw projectiles at enemies from a certain distance. Enemies will then receive damage if these projectiles were to hit and projectiles thrown should not be able to pass through obstacles like walls. 
 
## **Example**
- **Attack Distance**: Player will be able to damage enemies from a distance without the need to melee them. Logically, these projectiles should only travel a short distance (not endless)
- **Attack Direction**: Player will be able to attack enemies via different directions if required
 
# **Dependencies**
- [ ] Enemy (#10) - will need to confirm health of enemies, damage that will be taken when damage is received and etc.
 
# **Milestones**
- [ ] Documentation (Aug. 21)
- [ ] Locate methods related to allowing players to deal damage (Aug. 24)
- [ ] Sprite (placeholder) for directions visualization for player (when walking or attacking) (Aug. 25)
- [ ] Sprite (placeholder) for long range attacks (Aug. 25)
- [ ] Implement player's ability to execute long range attack (Aug. 26)
 
**Completion Deadline:** Aug. 26
 
# **Documentation**
- Will be included
 
# **Member**
- @25Ericcheong

**Comment by 25Ericcheong** [comment]
Combined with issue #36
