### ISSUE TITLE
Level Management Task: Game Over & Level Reset (Aug 30)

### ISSUE THREAD

**Issue by zhangyijia97** [UQdeco2800/2021-studio-6#31]
# **Description**
**Task:** [Game over and reset level](#3).
**Feature:** [Level management feature](#7 )
 
Within the level class:
- Implement the ability to reset level to the beginning when the option is selected (e.g. from game over menu or from an options menu)
- Have the game over screen show up when player health reaches 0. On the game over screen, a menu will appear, allowing players to restart level or quit game. When the game over screen is present, the game should be paused.
 
# **Dependencies**
- [x] Game over screen (#9)
- [x] #34
 
# **Milestones**
List of steps that need to be completed for this task.

- [x] Game over screen shows up (Aug. 27)
- [x] Game over screen menu (Aug 28)
- [x] Reset level function (Aug. 29)
 
**Completion Deadline:** Aug. 29
 
# **Documentation**
- [Main description of feature](../../wikis/page1)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**

**Comment by Bluehalomango** [comment]
Just wondering what you want to happen when the player dies? We have it in our branch that the player component gets dispossed but we can also call an event trigger that you can use after we die or the player has a isDead() function you can use. Do you know how you want it done?
