### ISSUE TITLE
Level Management Task: Pausing (Sept 1)

### ISSUE THREAD

**Issue by zhangyijia97** [UQdeco2800/2021-studio-6#34]
# **Description**
**Task:** [Pausing](#3).
**Feature:** [Level management feature](#7 )
 
Pausing the game using the ESCAPE key will temporarily stop every entity on the level (player and enemies) from moving or performing any action. Unpausing will cause them to resume whatever action they were performing.

A "placeholder" pause screen will be placed on top of the game screen when paused, when resumed, pause screen will disappear.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] All entities pauses correctly (Aug. 27)
- [x] All entities resumes correctly (Aug. 28)
- [x] Pausing screen show up correctly (Sept. 2)
 
**Completion Deadline:** Sept. 2
 
# **Member**
- Hai (@kainphoton) (Anh Hai Ho Chapman)
