### ISSUE TITLE
Level Management Task: Level Management Class (Sep. 1)

### ISSUE THREAD

**Issue by zhangyijia97** [UQdeco2800/2021-studio-6#35]
# **Description**
**Task:** [Level management class](#3).
**Feature:** [Level management feature](#7 )
 
The level management class will handle various aspects of each level, such as restarting level.
When a level is created, it should be attached(?) to the level management class as the current level, so that the level management class can act on the level when needed.
We will be responsible for creating classes from different game area in he game as well as the spawning method for the objects in the game area.
Before advancing to the next level, it must first go through the safehouse area, hence each level must be linked to the safehouse.

# **Dependencies**

# **Milestones**
List of steps that need to be completed for this task.
- [x] Created level management class
- [x] Write spawning methods for new objects
- [x] Create new game area classes for new levels
- [x] Make sure the levels are linked with the safehouse
- [x] Level can be created and displayed to the player (Sep. 1)
 
**Completion Deadline:** Sep. 1
 
# **Documentation**
- [Main description of feature](../../wikis/page1)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- @zhangyijia97 
- @Lumin-cider
