### ISSUE TITLE
Player Task: Long Ranged and Melee Attacks

### ISSUE THREAD

**Issue by 25Ericcheong** [UQdeco2800/2021-studio-6#36]
# **Description**
**Task:** Player Attack
**Feature:** #5 
 
The end of this task will also player to inflict melee attack and throw projectile attacks at enemies (directions specific depending on where mouse is clicked). This offers players the flexibility of being able to attack enemies which are too close or attack them at a range if players want to play it safe.
 
## **Example**
- **Long Ranged Attack Distance**: Player will be able to damage enemies from a distance without the need to melee them. Logically, these projectiles should only travel a short distance (not endless). Currently, the idea is that player will click with mouse (LMB) and a project would fire in the direction that is clicked in the game
- **Attack Direction**: Player will be able to attack enemies via different directions if required
- **Melee Attack**: Player will inflict melee damage to enemies which are within the range of components
 
# **Dependencies**
- [x] Enemy (#10) - will need to confirm health of enemies, damage that will be taken when damage is received and etc.
 
# **Milestones**
- [x] Documentation (Aug. 21)
- [x] Locate methods related to allowing players to deal damage (Aug. 22)
- [x] Trigger events when player collide with enemies in the game (Aug. 22)
- [x] Create conditions for players to time their melee attack when enemy is close enough (Aug. 22)
- [x] Implement melee attack (Aug. 22)
- [x] Collect relevant methods required for long ranged attack (Aug. 24)
- [x] ~~Produce projectiles when mouse (LMB) is clicked (with sprites provided)~~ Produce projectiles when key is clicked (L key) (Aug. 26)
- [x] Collision of projectile with enemy (if it hits)
- [x] Reduce health of enemies upon collision
- [x] ~~Dispose of projectile when it reaches coordinates of where mouse was clicked~~ Projectiles disposed when reaching the end boundaries of game screen or collides with any game world object
 
**Completion Deadline:** Aug. 27
 
# **Documentation**
- [Wiki ](https://github.com/UQdeco2800/2021-studio-6/wiki/Player-Attacks)
 
# **Member**
- @25Ericcheong 
- @SBHATTA19

**Comment by 25Ericcheong** [comment]
Issue combined from #30  and #23

**Comment by 25Ericcheong** [comment]
Completed and will be linked to pull request tomorrow.
