### ISSUE TITLE
Player Task: Dashing

### ISSUE THREAD

**Issue by tommps** [UQdeco2800/2021-studio-6#41]
# **Description**
**Task.** Dashing
**Feature:** #8 

Implementation of an additional dash on top of the players regular directional movement. When a button is pressed the player will be able to dash in their current direction of movement. During the short dash the player will be unable to change direction or take damage. 

# **Milestones**
- [x] Initial Documentation (Aug 28)
- [x] Implementation of increased movement in response to button press (Aug 30)
- [x] Implementation of invincibility frames (Aug 30)
- [x] Updating Documentation (Aug 30)
**Completion Deadline** Aug. 30

# **Documentation**
- [Player Movement](../../2021-studio-6/wiki/Player-Movement)

# **Member**
- Caitlin Thompson (@tommps) (Caitlin)

**Comment by tommps** [comment]
Completed without testing as currently incapable of doing so, will continue attempting unit testing before the completion of the sprint however likely to become a job for the next sprint.

**Comment by Skybluepanda** [comment]
I've had a read through all dash related code that's in the  main and I couldn't find anything related to dash ready for me to link implementation of dash cooldown bar.

Could you let me know if this feature is planned soon or postponed to next sprint?

**Comment by tommps** [comment]
> I've had a read through all dash related code that's in the main and I couldn't find anything related to dash ready for me to link implementation of dash cooldown bar.
> 
> Could you let me know if this feature is planned soon or postponed to next sprint?

The dash is implemented in [PlayerActions.java](https://github.com/UQdeco2800/2021-studio-6/blob/main/source/core/src/main/com/deco2800/game/components/player/PlayerActions.java#:~:text=if%20(dashing)%20%7B,dashing%20%3D%20false%3B) through applying a speed increase during movement. The dash cooldown is set in [KeyBoardPlayerInputComponent](https://github.com/UQdeco2800/2021-studio-6/blob/main/source/core/src/main/com/deco2800/game/components/player/KeyboardPlayerInputComponent.java#:~:text=case%20Keys.SHIFT_LEFT,%7D) through the games main timer. There is currently a method to check whether the player can currently dash based on the wait end time (basically the time of the last dash + the set delay). This is all also in the wiki page linked in the issue.

What information/methods did you need in top of this to implement the cooldown timer?

**Comment by Skybluepanda** [comment]
> What information/methods did you need in top of this to implement the cooldown timer?
> I could add another event trigger to set the cooldown as starting which also feeds through the cooldown time if that is appropriate to the method you have? Or a method to return the time currently remaining in the cooldown?

Thanks, didn't realise dash cooldown component would be in the input component section. I think it would be better if this if loop was handled by player action and combat stats component instead.

if (timeSource.getTime() >= waitEndTime) { // Check if player is allowed to dash again
          waitEndTime = timeSource.getTime() + DELAY_LENGTH; // Start timer for delay between dashes
          entity.getEvents().trigger("dash", INVINCIBILITY_LENGTH);
}

I could set up temporary counter that represents the cooldown outside of the input component for implementation of the hud for immediate use. But I'll try to take a look to see if I change it this sprint after I finish implementing health bar.

**Comment by tommps** [comment]
> > What information/methods did you need in top of this to implement the cooldown timer?
> > I could add another event trigger to set the cooldown as starting which also feeds through the cooldown time if that is appropriate to the method you have? Or a method to return the time currently remaining in the cooldown?
> 
> Thanks, didn't realise dash cooldown component would be in the input component section. I think it would be better if this if loop was handled by player action and combat stats component instead.
> 
> if (timeSource.getTime() >= waitEndTime) { // Check if player is allowed to dash again
> waitEndTime = timeSource.getTime() + DELAY_LENGTH; // Start timer for delay between dashes
> entity.getEvents().trigger("dash", INVINCIBILITY_LENGTH);
> }
> 
> I could set up temporary counter that represents the cooldown outside of the input component for implementation of the hud for immediate use. But I'll try to take a look to see if I change it this sprint after I finish implementing health bar, if you are too busy with other features.

The timer was implemented in the user controls so that a single time keeper and event could be used to trigger the dash and ensure either all/none of the functionality occurs (as it is watched by both playeractions to modify speed and playercombatstatscomponent to trigger invincibility).

Not sure what you mean by a temporary counter sorry, as in when dash is triggered you will start your own timer for the HUD based on the pre-existing dash event trigger?

**Comment by tommps** [comment]
> player action and combat stats component instead.

I have reimplemented the dash moving everything into playeractions (if you look at the player branches files it has all been pushed).
Main issue from changing it would be if you are using the dash event to run a cooldown timer the dash event is now trigger on attempt to dash not when dashing actually occurs.
Please let me know what you would like added to link into the cooldown timer.
