### ISSUE TITLE
Player Task: User Testing

### ISSUE THREAD

**Issue by ghost** [UQdeco2800/2021-studio-6#42]
# **Description**
**Task:** Player User Testing
**Feature:** #8 
 
Completion of user tests in order to gain an understanding of how the player approaches and interacts with the fundamental functions of the player within the game. Utilising basic task outlines and a thinking aloud process in order to evaluate the current functions within the game. In depth testing methodology and process is detailed within the wiki.
   
# **Milestones**
- [x] Writing up a testing plan (Aug 28)
- [x] Performing test plan on a first user (Aug 30)
- [x] Performing test plan on a second user (Aug 30)
- [x] Performing test plan on a third user (Aug 30)
- [x] Evaluating testing results (Aug 31)
**Completion Deadline:** Aug. 31
 
# **Documentation**
- [User Testing Player: Thinking Aloud](../../2021-studio-6/wiki/User-Testing-Player:-Thinking-Aloud)
 
# **Member**
- Caitlin Thompson (@tommps) (Caitlin)
- Lucas Bouwman (@Bluehalomango)
