### ISSUE TITLE
Player Task: Sprite Direction Animation Placeholder

### ISSUE THREAD

**Issue by Bluehalomango** [UQdeco2800/2021-studio-6#43]
# **Description**
**Task:** [Sprite Direction]().
**Feature:** [#8]

Implementation of sprite changes to player character corresponding to directional travel. The player sprite should be facing the direction that they are walking in i.e. if moving left, the character is looking left. During the current sprint, this will be implemented as a animation placeholder until the proper animations are created. Once they are finished, the referenced assets can be changed and applied seamlessly to the player.

# **Milestones**
List of steps that need to be completed for this task.
- [x] Initial Documentation(Aug. 29)
- [x] PlayerAnimationController Implementation (Aug. 30)
- [x] Directional Listeners (Aug. 30)
- [x] Final Documentation(Aug. 31)
 
**Completion Deadline:** Aug. 31
  
# **Documentation**
- [Player Appearance](../../2021-studio-6/wiki/Player-Appearance)
 
# **Member**
- Lucas Bouwman (@Bluehalomango)
