### ISSUE TITLE
Environment Task: Level 1 Layout

### ISSUE THREAD

**Issue by Lumin-cider** [UQdeco2800/2021-studio-6#57]
# **Description**
Level 1 will feature the start of the story and will act as a tutorial to how the game will play. Level 1 will be set in a post-apocalyptic city. The player will start from within the city, and have to escape into the forest to get away from the darkness/monsters.

# **Dependencies**
- #64 It is important to know how the story will progress so that levels can be designed appropriately.
- #97 
- #98 As level 1 will end with the players entering the forest, some of level 2's planned assets may be used

# **Milestones**
- [x] Layout of level planned (on paper)
- [x] Layout of level created with placeholder assets
- [x] Level populated with obstacles/enemies/etc
- [x] Level 1 completed with full assets

**Completion Deadline:** Sep. 15

# **Extras (optional)**
- [ ] Extra components that you may implement if you get time.
- [ ] ...

# **Documentation**
- [Main description of feature](../../wikis/Match%20Gameplay%20Rule%20Set)
- [User documentation](../../wikis/Game-Guide#section-five-cards)
- ...

# **Members**
