### ISSUE TITLE
Environment Task: Level 2 Layout

### ISSUE THREAD

**Issue by Lumin-cider** [UQdeco2800/2021-studio-6#58]
# **Description**
Level 2 game area will cover the middle portion of the story. The difficulty will be increased as the player is expected to be more familiar with the game. The player will traverse a forest, desperately trying to get to the next safehouse as they are constantly being chased.  The entities and tile sets positions will be hard coded.  

# **Dependencies**
- #64 It is important to know how the story will progress so that levels can be designed appropriately.
- #98 Implement the assets and tile sets design into the game area.

# **Milestones**
List of sub-features you intend to have done, and in Main, before the end of the sprint.
- [x] Layout of level planned (on paper)
- [x] Layout of level created with placeholder assets
- [x] Level populated with obstacles/enemies/etc
- [x] Level 2 completed with full assets

**Completion Deadline:** Sep. 15

# **Extras (optional)**
- [ ] Tileset designs

# **Members**
Hai @kainphoton 
Yunho @ayhlee
