### ISSUE TITLE
Level 3 - Level layout implementation with placeholders

### ISSUE THREAD

**Issue by Lumin-cider** [UQdeco2800/2021-studio-6#59]
**Task:** [Level 3 assets](#154) 
**Feature:** [Level 3](#151)

# **Description**
The layout of level 3 should be planned and implemented into the game.

# **Dependencies**
- Assets needed for level 3 (#154)

# **Milestones**
List of sub-features you intend to have done, and in Main, before the end of the sprint.
- [x] Layout of level 3 planned (on paper) (Oct. 1)
- [x] Level 3 implemented with placeholders (Oct. 3)
- [x] Level 3 implemented with finished assets (Oct. 5)

**Completion Deadline:** (Oct. 5)
