### ISSUE TITLE
Sprint 1 Team 4: Level Environment Feature

### ISSUE THREAD

**Issue by Hollycatsoulis** [UQdeco2800/2021-studio-6#6]
# **Description**
The development of level environment involves the creation of the game space of which the player explores. It has a crucial component to the game; the design and integration of elements should evoke the aesthetics, architecture and lore of the world.

This feature is to develop the initial concepts for the level environment and create the necessary structure to be expanded upon in future sprints. The key sub-features for the sprint are:
- Establishment of a level-specific theme for each level.
This involves the creation of a slightly modified style from the general style (color, theme, etc.) of the game. Examples include a forest, hills, icy mountain, desert, tundra or abandoned town biome.
> Team 1 (#9) are working on the interface of the home screen, and thus are best positioned to devise the general art style. 

- Introduction of Obstacles (area-based) and Items (point-based) (eg. prickly bushes (obstacle), health jug (item))
Obstacles are slightly harder to explain. These specific tiles cause an status modifier to entities within the boundary.
Items are currently modifiers for player stats (ie. add 10 health). Eventually (but not in this sprint), an inventory system may be introduced to add pickable items to assist the player on their journey.
> Multiple teams envision obstacles, however this subfeature aims to abstract these entities into two distinct classes; area and point-based. For effects, damage will be applied similar to how Enemies attack the Player (using the built in libGDX classes).

- Designing the background of the first few levels
> Pulling from [Inspiration](https://github.com/UQdeco2800/2021-studio-6/wiki/Game-Inspiration), our view of the map is a 2D top-down view of the player, however a slight tilt projection to add a simulated layer of depth may be desirable. This subfeature continues after a level-specific theme has been created.

- Location of various assets across the map (spawn location, locations of obstacles/items, location of safehouse)
> This does conflict with Team 5 (#7), however there is reason to argue that tight integration of location of entities along with the background design may be more effective. Discussion is in progress as to which team implements this.

### Subsequent background art

To fit the [storyline](https://github.com/UQdeco2800/2021-studio-6/wiki/Fireflies), three themes will need to be created. Three themes to properly establish are below. *Make more!!!*
1. Camp theme in a forest.
> **Lore:** The player is starting their journey. They are within a fairly well-lit camp, however the lights occasionally flicker. The player ventures into the forest to seek the next town. 

The forest is occasionally lit with torches, and the level acts as a easy level (maybe tutorial, maybe only a few easy enemies to introduce the concept, that could also be avoided)

2. Swamp
> **Lore:** Beware. Those who pass shall have to be worthy, and ready for a challenge.

Here is where we can add a simple riddle / maze aspect to the game. Addition of unique obstacles should increase the complexity, while not forcing the user to fight against enemies just yet. Mental challenges for the savvy.

3. Abandoned village
> **Lore:** The player is told of the eventual city of light along the journey (scrolls, wandering adventurers, some plot device). However as they get closer, they walk through abandoned villages, maybe people who have left for the city, maybe something more sinister. The creatures stalk around this area, so be wary and ready for combat.

Game is towards the end, and so we must increase the difficulty of the game. Enemies are a fairly difficult and dynamic obstacle, and so a zombie hoard requires the player to FIGHT!

### Obstacles / Items
Creation of ObstaclesClass and ItemsClass for the game environment. 
For this sprint, demonstrate interaction with the player. Easiest is to simply _hit_ the player or _add_ a specific amount of health points to the playerclass.
Extension, demonstrate interaction on NPCs.
> All future obstacles should be children of the ObstaclesClass. All future items should be children of the ItemsClass.

## **Examples (optional)**
See Description as to the examples.

# **Dependencies**
![NONE](https://img.shields.io/badge/-NONE-lightgrey)

# **Milestones**
List of sub-features intended to be implemented.
- [x] Write this feature
- [ ] Planning on general level design (size of map, number of levels, based on how many hours expected to play the game)
- [x] Level-specific themes (intended feeling and "expectation" from the player, art style, specific inspiration source, storyboards on desired interactions, music / sound effects), and subsequent lore.
- [ ] Background art (ie. generic placeholder, each level-specific background)
- [x] #3

**RECONSIDER**
- [ ] #11

**Feature Pre-Release:** Aug. 29 (Sunday)
**Completion Deadline:** Sep. 2 (Thursday)

# **Extras (optional)**
- [ ] Apply obstacle effects to enemies 
- [ ] Music / Sound Effects on obstacle / item interaction
- [ ] aesthetic-only obstacles (ie. flickering light)
- [ ] Animation of assets (ie. glowing health kit)

# **Documentation**
![TODO](https://img.shields.io/badge/-TODO-white)

# **Members**
- Holly Catsoulis (@Hollycatsoulis) (hollycatsoulis#5529)
- Cooper Lobegeiger (@cooperlobey) (cooperlobey#2338)
- Suhas Udupa (@suhasudupaa) (Huxley#5371)
- Anthony Chiam (@ultimate1112) (ultimate9121#4930)

**Comment by ultimate1112** [comment]
Stale issue.
Handled by future tickets.
