### ISSUE TITLE
Environment Task: Safehouse design

### ISSUE THREAD

**Issue by Lumin-cider** [UQdeco2800/2021-studio-6#60]
# **Description**
The safehouse acts as a safe area where the player is safe from enemies.
Here, the player can take a break, and shop for items (if implemented).
In this sprint, items will be implemented for players to interact with, to do so, changes to the safehouse will be required. Store will need to be implemented into the game area. This indicates that new textures will be needed.
Following from sprint 1, the door placeholder will be replaced with the newly created texture of the door.

# **Dependencies**
- #68 So that a shop can be prepared and interact with the inventory
- #62 So that items may be placed into the shop and be bought

# **Milestones**
List of sub-features you intend to have done, and in Main, before the end of the sprint.
- [ ] Safehouse layout completed
- [ ] door texture made and uploaded
- [ ] Shop completed

**Completion Deadline:** Sep. 15

# **Extras (optional)**
- [ ] Extra components that you may implement if you get time.
- [ ] ...

# **Documentation**
- [Main description of feature](../../wikis/Match%20Gameplay%20Rule%20Set)
- [User documentation](../../wikis/Game-Guide#section-five-cards)
- ...

# **Members**
