### ISSUE TITLE
Sprint 2 Team 2: Player Feature Extended

### ISSUE THREAD

**Issue by tommps** [UQdeco2800/2021-studio-6#61]
# **Description**
The player has already implemented the basic attack and movement methods (see #8), therefore this ticket will involve extensions and fixes to the base functionality to ensure engaging interactions and adding more dynamics to the game experience in terms of attacking and abilities.

This will include alterations to the players current attack system (both bug fixing previous implementations and having modifications from different melee attack weapons) as well as the addition of more feedback systems through animations to ensure the player has a strong awareness of what is occurring as they interact with the game.

## Sub Feature/Component
- Overhaul Melee Attack
    - Includes finishing directional melee attack from sprint 1 and making MeleeAttackComponent more variable based and extensibile
- Player Abilities
    - Covers four base abilities and the ability triggering system. Each ability should be a powerful action on a cooldown
         - Temporary Invincibility
         - Special Dash
         - Ranged AOE attack
         - Close-ranged Knockback
- Player Melee Weapon sprites
    - One sprite for each weapon class (Close-ranged, medium and long-ranged)
- Player Animations
    - Includes movement, attacking, dashing and getting hurt
- Health and dash interface
    - Have an animated interface that changes based on in-game actions
- Making ranged attacks ammo dependent
 
## **Examples**
- **Directional Melee Attack:** A bug fix/continuation from the previous sprint (see #46 #53), both allowing players to attack multiple times with having to re-enter the enemies boundary box and allowing the attacks to be in the set four directions 
- **Abilities:** The player will have an extra ability that can be triggered by a button and is set on a long cooldown in order to add another level to how players can effect the game. The player can only have one set ability out of: an AOE ranged attack, a set temporary invincibility, a long dash that will allow players to exit situations, a knockback that through releasing a wave of light the player can push enemies back.
- **Health & Dash Interface Triggering:** The HUD will show the players current health and whether or not the player can currently dash.

# **Dependencies**
- #68 Ammo dependency for ranged attack is dependent on the implementation of bullets to the inventory
 
# **Milestones**
- [x] #81 (08/09)
- [x] #85  (08/09)
- [x] #82 (08/09)
- [x] Weapon sprites - #107 (08/09)
- [x] #87 (08/09)
- [x] Weapon Animations - #107 (10/09)
- [x] Player Movement Animations (12/09)
- [x] #100 (13/09)
- [x] #88 (14/09)
- [x] #102 (15/09)
- [x] #101 (15/09)
- [x] Ensuring enough unit test coverage (15/09)
- [x] Finalisation of Documentation (15/09)

Sprint Due date = 16/09

# **Extras**
- [x] Player Taking Damage Animation
- [ ] Player Ability: Ranged AOE/grenade
- [ ] Player Ability: Knockback
- [x] Player Attack Animations - #107
- [ ] Additional Armour Sprites

# **Documentation**
- [Full description of player](../wiki/Player-Overview-Description)
 
# **Members**
- Caitlin Thompson (@tommps) (Caitlin)
- Eric Cheong Kai Kit (@25Ericcheong) (Eric)
- Jing Yang (@ydiannaj)
- Lucas Bouwman (@Bluehalomango)
- Sambit Bhattacharya (@SBHATTA19)
- Anthony Chiam (@ultimate1112)

**Comment by tommps** [comment]
EOS
