### ISSUE TITLE
Sprint 2 Team 3: Items Design

### ISSUE THREAD

**Issue by jadeomikaela** [UQdeco2800/2021-studio-6#62]
# Description
This ticket will focus on creating the graphics for the item pickups in the game. When the player kills an enemy, the items will drop on the ground, allowing the player to pick them up. These include bandages, (sugar, health potions), ammo and coins.

# Examples 
These will be used in the game when the player kills an enemy - multiple items will drop for the player to collect. They will have different effects on the player, which are outlined in #68 

# Dependencies
This depends on the player's team's item and inventory feature #68 

# Milestones
September 12 due date for all: 

- [x] bandage sprite (completed by team 2)
- [x] ammo sprite
- [x] coins sprite

### Extras
- [ ] sugar sprite (not necessary)
- [ ] health potion sprite (not necessary)

### Members
Holly Catsoulis @Hollycatsoulis

**Comment by tommps** [comment]
Final Item List:
Consumable items (sprites should be around the same size & need grayscale/crossed-out version as well as regular version -> showing if player has the items)
* Bandage sprite
* Sugar sprite
* Health potion sprite
Other Items: (just need the regular version)
* Ammo sprite (will also be used as projectile -> a rock)
* Coins sprite
(and animations if at all possible -> for when they are on the ground to be picked up)

**Comment by jadeomikaela** [comment]
> Final Item List:
> Consumable items (sprites should be around the same size & need grayscale/crossed-out version as well as regular version -> showing if player has the items)
> 
> * Bandage sprite
> * Sugar sprite
> * Health potion sprite
>   Other Items: (just need the regular version)
> * Ammo sprite (will also be used as projectile -> a rock)
> * Coins sprite
> 
> (and animations if at all possible -> for when they are on the ground to be picked up)
> 
> (may need to be changed a bit depending on story and environment and what is appropriate)

hey, thanks for getting this in! For sugar I was a bit confused. Did you want a sugar cube? let me know and send a few inspiration ideas :)

**Comment by tommps** [comment]
Sorry, after talking to Hannah on feature ticket and a meeting we had to change some item plans,
Updates to items:
* Coin (32x32 for the standard size + animation for when on ground if possible)
* Ammo (rock, probably closer to 16x16 in size, but could do 32x32 to give scaling options for later) (+ animation for on ground if possible)
* Could also help with HUD element designs when we get to the final HUD but that's later on the feature ticket/might be too much work on top of any other tasks, let us know.

**Comment by Hollycatsoulis** [comment]
> Sorry, after talking to Hannah on feature ticket and a meeting we had to change some item plans,
> Updates to items:
> 
> * Coin (32x32 for the standard size + animation for when on ground if possible)
> * Ammo (rock, probably closer to 16x16 in size, but could do 32x32 to give scaling options for later) (+ animation for on ground if possible)
> * Could also help with HUD element designs when we get to the final HUD but that's later on the feature ticket/might be too much work on top of any other tasks, let us know.

sure that's all good I will get started on those items ASAP

**Comment by 25Ericcheong** [comment]
Hey! Used the rock sprite in the game and it look noice. Just send a message when the coin sprite has been pushed to main so i can test that out too.

**Comment by Hollycatsoulis** [comment]
Hey just committed it to the main
