### ISSUE TITLE
Enemies Task: Animation

### ISSUE THREAD

**Issue by Hollycatsoulis** [UQdeco2800/2021-studio-6#63]
# Description
Animation of all enemies moving left and right, attack animations, and other animations needed to be done

# Subfeatures

# Examples 

# Dependencies
This depends on multiple tickets:

### Milestones
- [x] walking for some enemies
- [x] idling - large enemy
- [x] large enemy left and right
- [x] long range enemy left and right
- [x] small enemy left and right
- [ ] short range enemy left and right
- [x] large enemy attack
- [x] small enemy attack
- [ ] short range enemy attack

### Documentation

Animations for the large enemy have been unticked, as a different design style is needed
### Extras
- [ ] seeing the player - make different somehow (eye reds)  
- [ ] being attacked - might not have to do it, depends on coders
- [ ] dying
- [ ] spawning animation
- [ ] long range enemy attack
### Members
Holly Catsoulis @Hollycatsoulis
Crystal Yu @quartz-c
Jade Taylan @jadeomikaela
