### ISSUE TITLE
Sprint 2 Team 1: Story Feature

### ISSUE THREAD

**Issue by ScariestWheat** [UQdeco2800/2021-studio-6#64]
# **Feature: Story**
In this sprint, we will be implementing the story of the main game through different features. This will involve the creation and implementation of prologue and epilogue stories, a game over screen, music and a pause menu screen.

The story as a feature is vital to the game's success and playability. Through the different elements within this feature, the story of the game will be more fleshed out and will enhance the user's immersion with the game and it's storyworld.

If time permits, we will also like to include more story elements between the levels.    

### Story Manager
We will write a class that records the player’s progression through the story. It will control advancing through levels, the win/lose condition and story-telling through dialogue boxes. 

### Music
The background music for the prologue, main game, and epilogue. 

### Prologue
An introductory scene that begins when the player chooses *Start* on the main menu. It establishes the setting before the first level is loaded.

### Epilogue
A story segment of what happens after the player “wins” the game.

### Game Over
A screen that is shown when the player meets a losing condition (e.g. no health).

### Pause Menu
Pausing the game brings up the pause menu.

While paused, the player can
- Resume game
- Exit to menu
- Exit game
- Restart game/level (optional)
- Open settings (optional)

## **Dependencies**
- [ ] Game Story Overview: The story idea must be finalised and approved by the studio.(https://github.com/UQdeco2800/2021-studio-6/wiki/Story-Overview).

# **Milestones**
- [x] #73
- [x] #74
- [x] #75
- [x] #76
- [x] #77
- [x] #78

**Completion Deadline:** Thursday 16 September 2021, 4:00pm

# **Extras (optional)**
- [ ] Story scene between level 1 and level 2
- [ ] Story scene between level 2 and level 3
- [ ] Do research on game design and make design decisions to make the game fun.

# **Documentation**
- [Story Overview](https://github.com/UQdeco2800/2021-studio-6/wiki/Story-Overview)
- [Story Scene Design](https://github.com/UQdeco2800/2021-studio-6/wiki/Story-Scene-Design-Documentation)
- [Story Manager](https://github.com/UQdeco2800/2021-studio-6/wiki/Story-Manager)
- [Pause Menu](https://github.com/UQdeco2800/2021-studio-6/wiki/Pause-Menu)
- [Game Over Screen](https://github.com/UQdeco2800/2021-studio-6/wiki/Game-Over-Screen)
- [Music](https://github.com/UQdeco2800/2021-studio-6/wiki/Music)

# **Members**
- Brian Stewart (@DancingBrian) (Brian#8636)
- Chris Kang (@Skybluepanda) (Bluepanda#5218)
- Laura Johnston (@ScariestWheat) (ScariestWheat#5492)
- Renée (@NightingaleUQ) (Renée)
- Joseph (@implex001) (implex001#2331)
- Suhas (@suhasudupaa) (Huxley#5371)

**Comment by Bluehalomango** [comment]
Just letting y'all know that the 'Continue' button on the 'Pause' screen currently does nothing. Not sure if you plan on fixing that or just removing the button though.

**Comment by DancingBrian** [comment]
> 
> 
> Just letting y'all know that the 'Continue' button on the 'Pause' screen currently does nothing. Not sure if you plan on fixing that or just removing the button though.

Thanks for letting us know, will check it out :)
