### ISSUE TITLE
Enemies Task: Sound Effects

### ISSUE THREAD

**Issue by Hollycatsoulis** [UQdeco2800/2021-studio-6#67]
# Description
Sound effects, sourcing and coding for all enemy types. Sound for both enemy attack and enemy death, while some other items may also be added in the future.

# Examples
Large enemy attack: When the large enemy gets too close to the player, a sound will play as the attack animation plays.
Collection of items: When the enemy is killed, there will be items that the player collection. Upon collecting the items, there will be a sound that plays. An extra feature if we get time will be to make different sounds for each item.

# Dependencies
This depends on multiple tickets:
- [ ] Items Design #62 
- [ ] Items Code (no ticket yet)

# Milestones

## Programming
- [ ] implementing large enemy attack sound 
- [ ] implementing long range enemy attack sound 
- [ ] implementing small enemy attack sound
- [ ] implementing short range enemy attack sound
- [ ] implementing collection of items sound

## Design
- [x] Large enemy attack sound 
- [x] Long range enemy attack sound 
- [x] Small enemy attack sound
- [x] Short range enemy attack sound
- [x] Collection of items sound

# Documentation

## Extras
- [ ] Different sounds for each item when player picks them up

### Members
Niklas Matha @nikmatha 
Hamish Killen @Hamish-Killen 
Matthew Holloway @yourlow 
Crystal YU @quartz-c 
Holly Catsoulis @Hollycatsoulis 
Jade Taylan @jadeomikaela
