### ISSUE TITLE
Sprint 2 Team 2: Item/Inventory Feature

### ISSUE THREAD

**Issue by 25Ericcheong** [UQdeco2800/2021-studio-6#68]
# **Description**
The setup of an inventory and item system for the player to collect, hold, and use items during the game. These consumable items will be displayed on screen during the game, allowing the player to know whether they have the item and through pressing the correct hotkey the player will use them (this also includes the player ammo).

Additionally this feature includes multiple melee weapons which have different attack damages, speeds and ranges. Only one melee weapon can be used at a time.
 
## Sub Feature/Component
- Three different set melee weapons
    - At the moment, these are classified as short range, medium range and long range classes
- Pickup Item Component
    - A physical component should be made that allows players to interect with items in the game environment, adding directly to their inventory and applying their immediate affect
- Usable Item Component
    - A separate non-physical component should be used to facilitate using items once the player has picked it up. This should be extensibile or otherwise compatable with the individual consumable items
- Consumable Items
    - Bandages (Heals wounds)
- Currency
    - Used to buy upgrades and items in the safehouse
    - Also covers interaction with enemies and buying items
- Ammo
    - Pickup dropped from enemies/found that gives the player additional ranged ammo
- Inventory HUD
    - Player interface that displays the various consumables as well as amounts and hotkeys for each of them
- Armor
    - The player should be able to buy armor at the safehouse that increases their defense values to reduce enemy damage
    - Each armor upgrade is an additional piece of armor for the character
 
## **Examples**
- **Multiple Melee Weapons:** The player will be set from the beginning of the game to have one of three possible melee weapons. This includes a short range weapon (which attacks faster, deals less damage and has a shorter attack range), a medium range weapon (has a standard damage, speed and range) and a long ranged weapon (which attacks slower but deals more damage in a wider radius)
- **Pickup able Items:** When the player walks over the item on the ground in the game the player will collect the item
- **Usable Items:** When the player presses the corresponding number key that item will be used and the HUD will display the player no longer having it
- **Consumable Items:** The player will have ~four~ one consumable  items; bandages (increase the players wound state) ~health potion (increase the players health), sugar (increase the players speed temporarily)~

# **Dependencies**
- #62 Finalised HUD depends on the design and creation of item assets
 
# **Milestones**
- [x] #90  (13/09)
- [x] #96 (13/09)
- [x] #89  (13/09)
- [x] Currency item (14/09)
- [x] Hotkeys for consumables	(14/09)
- [x] Ammo pickup (15/09)
- [x] Bandage item - #107 (15/09)
- [x] #106 (15/09)
- [x] Finalisation of documentation (16/09)

Sprint Due date = 16/09

# **Extras**
- [x] #99 
- [x] Medium melee config file
- [x] First Armor Upgrade Pickup
- [x] Short ranged melee config file
- [x] Long ranged melee config file
- [x] Finalised Item HUD
- [x] Second Armour Upgrades Pickup
- [x] Torch item - #107 
- [ ] Weapon tiers
 
# **Documentation**
- [Wiki ](https://github.com/UQdeco2800/2021-studio-6/wiki/Player-Inventory-and-Pickup-Items)  
 
# **Members**
- Caitlin Thompson (@tommps) (Caitlin)
- Eric Cheong Kai Kit (@25Ericcheong) (Eric)
- Jing Yang (@ydiannaj)
- Lucas Bouwman (@Bluehalomango)
- Sambit Bhattacharya (@SBHATTA19)
- Anthony Chiam (@ultimate1112)

**Comment by 25Ericcheong** [comment]
Currently waiting on coin sprite item to be tested and used in game.

**Comment by tommps** [comment]
EOS
