### ISSUE TITLE
Sprint 1 Team 5: Level Management Feature

### ISSUE THREAD

**Issue by kainphoton** [UQdeco2800/2021-studio-6#7]
# **Description**
The level management feature is contingent on many other features such as players, enemies, environment and interface. For example, in order to reset the game, the player may be led to a dead-end, an obstacle or have no remaining health (has died). 
 
### **Level Management Class**
A class to manage aspects of each level (e.g. pausing, restarting).
As more features are added to the game, the level management class will be updated accordingly.
### **Safehouse**
The level can contain safehouses which act as transitions between levels:
- When players reach the end of a level, they will be moved to a safehouse map/room where they'll be safe from enemies.
- By moving to the other end of the safehouse, the player will be able to enter the next level.

Additional functionality (to be discussed further in future sprints):
- Ability to save/load game while in safehouse
- A shop where players can buy, trade and sell in-game items
- Ability to upgrade the safehouse for more features/functionalities?
### **Reset Level**
When a player selects the restart level option (on the game over screen or from a menu), the level will be reset to the beginning.
### **Game Over**
When the player's health reaches 0 (or has otherwise died), play a death animation(?) and bring up a "game over" screen. Players will be given options to restart level/quit.
### **Camera Movement**
When the player moves, the screen/camera should move with the player. (Optional): The camera should not move past the edge of the level. A way for the player to pan the camera without moving.
### **Pausing**
When the pause button is pressed or when the game over screen is activated, the game will be paused and an appropriate menu (pause menu/game over options) will be brought up.
 
## **Assets Required**
- Safehouse tile(s) in level
- Safehouse transition screen/"mini level"
- "Game over" screen

# **Dependencies**
 - #8 #9 : In order to check and decide whether the player has lost the current level by reaching 0 health.
 - #9 : "Game over" interface, consequently display multiple options for player (i.e. Reset level, restart from checkpoint, quit game, etc.)
 - #8 : For camera movement to be functional and following the player, it is required that multiple factors be verified periodically. For instance, whether the player is alive (or not) for the camera to follow.
 
# **Milestones**
List of sub-features you intend to have completed and merged in Master by the end of the sprint.
- [x] #33
- [x] #34
- [x] #31 
- [x] #32
- [x] #35
 
**Completion Deadline:** 4pm Sep. 2
 
# **Extras (optional)**
- [ ] Ability to save/reload
- [ ] Restart Level without dying
- [ ] Camera stops at the edge of the level
 
# **Documentation**
- [Main description of feature](../../wikis/page1)
- [User documentation](../../wikis/Game-Guide#section1)
- ...
 
# **Members**
- Hai (@kainphoton) (Anh Hai Ho Chapman) 
- Yunho (@ayhlee) (Yunho Lee)
- Yijia (@zhangyijia97) (Yijia Zhang)
- Patrick (@Lumin-cider) (Cheng-Yu Lin)
- James (@BungyStudios) (James Kebung Chen-Smith)
