### ISSUE TITLE
Story Task - Story Manager (Sep. 15th)

### ISSUE THREAD

**Issue by DancingBrian** [UQdeco2800/2021-studio-6#73]
Story Manager
# **Description**
**Task:** Story Manager
**Feature:** Story (#64)
 
The story manager is a class that tracks the current progress of the story and displays a story element when necessary. 

![image](https://user-images.githubusercontent.com/88139197/132115799-db63b168-84c6-4029-a0ae-ce8dca81a20c.png)

# **Dependencies**
None
  
# **Milestones**
- [x] Creation of story manager documentation
- [x] Implementation of Storybase 
- [x] Implementation of CutScene
- [x] Implementation of Story Manager
- [x] Creation of unit and integration tests
- [x] Finalising of story manager documentation
 
**Completion Deadline:** Sep 15th
 
# **Extras**
- [ ] Non linear triggers of stories
- [x] Conversion of legacy dialogue box calling into StoryManager ones

# **Documentation**
- [Story Manager](https://github.com/UQdeco2800/2021-studio-6/wiki/Story-Manager)
 
# **Member**
- Joseph (@implex001) (implex001#2331)
- Chris Kang (@Skybluepanda) (Bluepanda#5218)
