### ISSUE TITLE
Story Task - Prologue (Sep. 15th)

### ISSUE THREAD

**Issue by DancingBrian** [UQdeco2800/2021-studio-6#74]
# **Description**
**Task:** Prologue
**Feature:** Story (#64)
 
This task is to focus on the creation of the prologue scenes and screenplay. This will be done through storyboarding and screenwriting which will then be created with still art (maybe some simple animation if time permits) and dialogue. This will then be implemented into the game through the story manager (#73).

This prologue is to help users grasp the story concept and immerse them into the gaming experience. The purpose of the prologue within the game is to immerse the user into the storyworld and it's environment. It will also provide context to why they have to run from darkness, and why they must venture on this quest to find the safe haven. The prologue will also provide character context and place the user within the player's story.

# **Dependencies**
- [x] Game Story: The story idea must be finalised and approved by the studio before the prologue can be produced (https://github.com/UQdeco2800/2021-studio-6/wiki/Story-Overview).
- [x] Story Manager: The story manager will be used to display the prologue at the start of the game. #73  
  
# **Milestones**
- [x] Finalise Overall Game Story with studio approval (Sep 11th) 
- [x] Create prologue section within the story wiki documentation (Sep 11th) 
- [x] Storyboard Prologue (Sep 12th) 
- [x] Screenplay - dialogue & scenes (Sep 12th) 
- [x] Creation of Visuals (Sep 13th) 
- [x] Implementation of Scenes (story manager #73) (Sep 13th) 
- [x] User testing (Sep 14th) 
- [x] Implement user feedback (Sep 15th)
- [x] Finalise prologue section within the story wiki documentation (Sep 15th) 

**Completion Deadline:** Sep 15th

 # **Extras**
-  Music and Sound (#78)
-  Spoken Dialogue (VA)
-  Scene Animation

# **Documentation**
- [Story Overview](https://github.com/UQdeco2800/2021-studio-6/wiki/Story-Overview)
- [Story Scene Design](https://github.com/UQdeco2800/2021-studio-6/wiki/Story-Scene-Design-Documentation)
 
# **Member**
- Laura Johnston (@ScariestWheat) (ScariestWheat#5492)
- Suhas (@suhasudupaa) (Huxley#5371)
- Joseph (@implex001) (implex001#2331)
- Chris Kang (@Skybluepanda) (Bluepanda#5218)
- Renée (@NightingaleUQ) (Renée)
