### ISSUE TITLE
Story Task - Epilogue (Sep. 15th)

### ISSUE THREAD

**Issue by DancingBrian** [UQdeco2800/2021-studio-6#75]
# **Description**
**Task:** Epilogue
**Feature:** Story (#64)
 
This task is to produce and implement the epilogue story for the end of the game. This will be done through storyboarding and screenwriting which will then be created with still art (maybe some simple animation if time permits) and dialogue. This will then be implemented into the game through the story manager (#73).
The epilogue is to complete the story of the game so the users feel a sense of achievement and satisfaction after completing the gameplay and story.

# **Dependencies**
- [ ] Game Story: The story idea must be finalised and approved by the studio before the epilogue can be fully produced. (https://github.com/UQdeco2800/2021-studio-6/wiki/Fireflies)
- [ ] Story Manager: The story manager will be used to display the epilogue at the end of the game. #73  
  
# **Milestones**
- [x] Finalise Overall Game Story with studio approval (Sep 11th)
- [x] Create epilogue section within the story wiki documentation (Sep 11th)
- [x] Storyboard Epilogue (Sep 12th)
- [x] Screenplay - dialogue & scenes (Sep 12th)
- [x] Creation of Visuals (Sep 13th)
- [x] Implementation of Scenes (story manager #73) (Sep 13th) 
- [x] User testing (Sep 14th) 
- [x] Implement user feedback (Sep 15th)
- [x] Finalise epilogue section within the story wiki documentation (Sep 15th) 

**Completion Deadline:** Sep 15th

 # **Extras**
- [ ] Spoken Dialogue
- [ ] Scene Animation
- [ ] Music and Sound (#78)

# **Documentation**
- [Story Overview](https://github.com/UQdeco2800/2021-studio-6/wiki/Story-Overview)
- [Story Scene Design](https://github.com/UQdeco2800/2021-studio-6/wiki/Story-Scene-Design-Documentation)
 
# **Member**
- Laura Johnston (@ScariestWheat) (ScariestWheat#5492)
- Suhas (@suhasudupaa) (Huxley#5371)
- Joseph (@implex001) (implex001#2331)
- Chris Kang (@Skybluepanda) (Bluepanda#5218)
- Renée (@NightingaleUQ) (Renée)
