### ISSUE TITLE
Story Task - Game Over Screen (Sep. 15th)

### ISSUE THREAD

**Issue by DancingBrian** [UQdeco2800/2021-studio-6#76]
# **Description**
**Task:** Game Over
**Feature:** Story (#64)
 
The Game Over screen will be displayed whenever the player meets a losing condition, for example when the player is dead. Within the game over screen will be an option to return to the main menu or quit the game.
 
# **Dependencies**
None
  
# **Milestones**
- [x] Create game over documentation (Sep 6th)
- [x] Game Over screen draft design/layout (Sep 7th)
- [x] Game Over implement draft design/layout (Sep 7th)
- [x] Transition to game over screen when game ends (Sep 8th)
- [x] Add option for player to return to menu and to quit the game (Sep 8th)
- [x] Add sound effects for button rollover and click (Sep 8th)
- [x] Update game over documentation (Sep 9th)
- [x] Finalise design/layout (Sep 14th)
- [x] Finalise game over documentation (Sep 15th)

**Completion Deadline:** Sep 15th

# **Documentation**
- [Game Over Screen](https://github.com/UQdeco2800/2021-studio-6/wiki/Game-Over-Screen)
 
# **Member**
- Brian Stewart (@DancingBrian) (Brian#8636)
- Chris Kang (@Skybluepanda) (Bluepanda#5218)

**Comment by Skybluepanda** [comment]
Hey Brian I updated the wiki, and did some research. And I think we should wait until our MVP gives the game a clear identity of what kind of game it wants to be and then add features to game over screen that will benefit the type of game it becomes.
For now, the buttons in the current build is enough and if you want, I could make a design to replace the pitch black screen for the current sprint.
