### ISSUE TITLE
Story Task - Pause Menu (Sep. 15th)

### ISSUE THREAD

**Issue by DancingBrian** [UQdeco2800/2021-studio-6#77]
# **Description**
**Task:** Pause Menu
**Feature:** Story (#64)
 
The pause menu will display as an overlay when the user pauses the game. The pause menu will contain options to continue, exit to menu, and to exit the game.
 
# **Dependencies**
None
  
# **Milestones**
- [x] Create pause menu documentation (Sep 6th)
- [x] Pause menu draft design/layout (Sep 7th)
- [x] Pause menu implement draft design/layout (Sep 7th)
- [x] Add option for player to continue (Sep 8th)
- [x] Add option for player to return to menu and to quit the game (Sep 8th)
- [x] Add sound effects for button rollover and click (Sep 8th)
- [x] Update pause menu documentation (Sep 9th)
- [x] Finalise design/layout (Sep 12th)
- [x] Finalise pause menu documentation (Sep 15th)

**Completion Deadline:** Sep 15th
 
 # **Extras**
- [x] Add option for settings menu
- [x] Implement the settings options within the pause menu

# **Documentation**
- [Pause Menu](https://github.com/UQdeco2800/2021-studio-6/wiki/Pause-Menu)
 
# **Member**
- Brian Stewart (@DancingBrian) (Brian#8636)
- Chris Kang (@Skybluepanda) (Bluepanda#5218)
