### ISSUE TITLE
Story Task - Music (Sep. 15th)

### ISSUE THREAD

**Issue by DancingBrian** [UQdeco2800/2021-studio-6#78]
# **Description**
**Task:** Music
**Feature:** Story (#64)
 
This task involves the composition and playback of music throughout the entire game. In Sprint 1 only music for the Start-Up/Title screen was composed. In this sprint we will expand the presence of music to the game itself. This includes:

- Background music during gameplay
- Background music for Prologue/Epilogue
- Background music for Safe House
 
# **Dependencies**
- [x] Finalisation of storyboard for prologue and epilogue music

# **Milestones**
- [x] Deciding on a consistent music style that is going to be used throughout the game.
- [x] Compose the tracks individually and combine them using appropriate software.
- [x] Review of the tracks with the team for improvements/feedback
- [x] Integrate tracks into the game and ensure sync stays right.

**Completion Deadline:** 12th of September (in time for user testing)

- [x] User testing
- [x] Create music design documentation

**Completion Deadline:** 15th of September

# **Extras**
Sound Effects like:
- Player damage, 
- Enemy fire, 
- Successful/unsuccessful level completion,
- Starting a new level

# **Documentation**
- [Music](https://github.com/UQdeco2800/2021-studio-6/wiki/Music)
 
# **Members**
- Renée (@NightingaleUQ) (Renée)
- Laura Johnston (@ScariestWheat) (ScariestWheat#5492)
- James Chen-Smith from Team 5 (@BungyStudios)
