### ISSUE TITLE
Sprint 1 Team 2: Player Feature

### ISSUE THREAD

**Issue by 25Ericcheong** [UQdeco2800/2021-studio-6#8]
# **Description**
The Player feature is the creation of a player controlled character and involves all basic attributes contributing to the user’s interactions within the game world. This includes appearance, feedback, movement, environmental collision handling as well as player statistics. Necessary for the minimum viable product in order to make the game interactive and player driven.
When playing the game, the player sprite will represent the user's location and keyboard controls will allow movement so the player can interact with the environment; either through blockades, item collection or taking/dealing damage. Animations will provide the user feedback on both their inputs and interactions with the environment. Health/dying will report the response of these interactions to the player.
 
## Sub Feature/Component
- Health + Dying
- Player Statistics
- Appearance
- Animations
- Environment Collision
- Attacks (Short/Long Ranged)
- Item Interaction
 
## **Examples**
- **Health**: Health is deducted when player is attacked by enemies and result in various stages of damaged (minor, medium, severe), once the player reaches the highest damaged state, a subsequent attack will result in the death event. 
- **Stats**: These include the movement speed, attack damage and defence level of the player. The players movement speed and attack damage will be set at the beginning and change as the player reaches higher levels of wounded, while the defence level will simply alter the amount of damage a player takes when attacked.
- **Appearance**: The design of the player. Design/appearance will include design of character from different angles, appearance of dying or when taking damage.
- **Extras: Animations**: Actions like walking, taking damage, dying etc. Would be animated (or at least designed to look like it is animated to the user) to enhance user's experience and aesthetic looks.
-  **Extras: Dodge/Dash**: The player can dodge or dash through enemies and attacks to give them immunity/resistance.

# **Dependencies**
- #10 #6 Interaction (enemy attacks and collision with environment). Will need to consider how close or far an enemy will need to be when engaging with player in terms of attacking and there may be obstacles or barriers in the environment where player will not be able cross or run over
- #7 Level management (movement, character progression, dying). In terms of character progression and dying, continuous communication with team involved in level management will be required to ensure how level will respond to the occasion of player dying or when player progresses (this can be when player progresses through levels)
 
# **Milestones**
- [x] Initial Documentation (22 August)
- [x] #18  (23 August)
- [x] #20 (24 August)
- [x] #17 (26 August) 
- [x] [Player Task: Melee Attack](https://github.com/UQdeco2800/2021-studio-6/issues/36) (26 August)
- [x] [Player Task: Long Range Attack](https://github.com/UQdeco2800/2021-studio-6/issues/36)  (28 August)
- [x] #27 (30 August)
- [x] #42 (31 August)
- [x] Final Documentation (1 September)

Note. Milestones are subjected to change and will be discussed in-depth. Currently, it is arranged in the order of what needs to be completed first from top to bottom. 
 
# **Extras**
- [x] #41 (30 August)
- [x] #43 (31 August)
- [ ] Animations
- [ ] Item Interaction
- [ ] Attacking sprites

Note. These are tasks that are deemed extras as they are not as essential currently for the game to at least function and be playable. These will be targeted if time permits and all core tasks are completed.
 
# **Documentation**
- [Full description of player](../wiki/Player-Overview-Description)
 
# **Members**
- Caitlin Thompson (@tommps) (Caitlin)
- Eric Cheong Kai Kit (@25Ericcheong) (Eric)
- Jing Yang (@ydiannaj)
- Lucas Bouwman (@Bluehalomango)
- Sambit Bhattacharya (@SBHATTA19)

**Comment by addiii4** [comment]
> # **Description**
> The Player feature is the creation of a player controlled character and involves all basic attributes contributing to the user’s interactions within the game world. This includes appearance, feedback, movement, environmental collision handling as well as player statistics. Necessary for the minimum viable product in order to make the game interactive and player driven.
> When playing the game, the player sprite will represent the user's location and keyboard controls will allow movement so the player can interact with the environment; either through blockades, item collection or taking/dealing damage. Animations will provide the user feedback on both their inputs and interactions with the environment. Health/dying will report the response of these interactions to the player.
> 
> ## SubFeature/component
> * Health and stats
> * Movement and Controls
> * Appearance
> * Animations
> * Environment Collision
> * Attacks
> * Taking damage
> * Dying
> 
> ## **Examples**
> * **Health & Stats**: Linked to player’s profile. Stats would improve (or get worse if player dies) as player progress through levels (or checkpoints). Health is deducted when player is attacked by enemies and would change colors (possibly from green to yellow to red) to magnify the possibility of player dying continuously
> * **Movement & Controls**: Arrow or WASD keys will be binded for player movements (moving left, right, down or up)
> * **Appearance**: The design of the player. Design/appearance will include design of character from different angles, appearance of dying or when taking damage.
> * **Taking Damage**: When player receives damage, health bar will decrease if player is unable to dodge incoming projectiles or melee attacks from enemies
> 
> # **Dependencies**
> * Interaction (enemy attacks and collision with environment). Will need to consider how close or far an enemy will need to be when engaging with player in terms of attacking and there may be obstacles or barriers in the environment where player will not be able cross or run over
> * Level management (movement, character progression, dying). In terms of character progression and dying, continuous communication with team involved in level management will be required to ensure how level will respond to the occasion of player dying or when player progresses (this can be when player progresses through levels)
> 
> # **Milestones**
> * [ ]  Appearance (23 August)
> * [ ]  Movement & Controls (23 August)
> * [ ]  Health & Stats (26 August)
> * [ ]  Animations (28 August)
> * [ ]  Environments Collision (30 August)
> * [ ]  Item Interaction (31 August)
> * [ ]  Dying (31 August)
> 
> Note. Milestones are subjected to change and will be discussed in-depth. Currently, it is arranged in the order of what needs to be completed first from top to bottom.
> 
> # **Extras**
> * [ ]  Attacks
> * [ ]  Item Collection (inventory or picking up potions as you go)
> * [ ]  Abilities
> 
> Note. These are tasks that are deemed extras as they are not as essential currently for the game to at least function and be playable. These will be targeted if time permits and all core tasks are completed.
> 
> # **Documentation**
> * To be updated
> 
> # **Members**
> * Caitlin Thompson (@tommps) (Caitlin)
> * Eric Cheong Kai Kit (@25Ericcheong) (Eric)
> * Jing Yang (@ydiannaj)
> * Lucas Bouwman (@Bluehalomango)
> * Sambit Bhattacharya (@SBHATTA19)
> * Aditya Singh Cheema (@addiii4)

**Comment by HannahHinckfuss** [comment]
> > # **Description**
> > The Player feature is the creation of a player controlled character and involves all basic attributes contributing to the user’s interactions within the game world. This includes appearance, feedback, movement, environmental collision handling as well as player statistics. Necessary for the minimum viable product in order to make the game interactive and player driven.
> > When playing the game, the player sprite will represent the user's location and keyboard controls will allow movement so the player can interact with the environment; either through blockades, item collection or taking/dealing damage. Animations will provide the user feedback on both their inputs and interactions with the environment. Health/dying will report the response of these interactions to the player.
> > ## SubFeature/component
> > 
> > * Health and stats
> > * Movement and Controls
> > * Appearance
> > * Animations
> > * Environment Collision
> > * Attacks
> > * Taking damage
> > * Dying
> > 
> > ## **Examples**
> > 
> > * **Health & Stats**: Linked to player’s profile. Stats would improve (or get worse if player dies) as player progress through levels (or checkpoints). Health is deducted when player is attacked by enemies and would change colors (possibly from green to yellow to red) to magnify the possibility of player dying continuously
> > * **Movement & Controls**: Arrow or WASD keys will be binded for player movements (moving left, right, down or up)
> > * **Appearance**: The design of the player. Design/appearance will include design of character from different angles, appearance of dying or when taking damage.
> > * **Taking Damage**: When player receives damage, health bar will decrease if player is unable to dodge incoming projectiles or melee attacks from enemies
> > 
> > # **Dependencies**
> > 
> > * Interaction (enemy attacks and collision with environment). Will need to consider how close or far an enemy will need to be when engaging with player in terms of attacking and there may be obstacles or barriers in the environment where player will not be able cross or run over
> > * Level management (movement, character progression, dying). In terms of character progression and dying, continuous communication with team involved in level management will be required to ensure how level will respond to the occasion of player dying or when player progresses (this can be when player progresses through levels)
> > 
> > # **Milestones**
> > 
> > * [ ]   Appearance (23 August)
> > * [ ]   Movement & Controls (23 August)
> > * [ ]   Health & Stats (26 August)
> > * [ ]   Animations (28 August)
> > * [ ]   Environments Collision (30 August)
> > * [ ]   Item Interaction (31 August)
> > * [ ]   Dying (31 August)
> > 
> > Note. Milestones are subjected to change and will be discussed in-depth. Currently, it is arranged in the order of what needs to be completed first from top to bottom.
> > # **Extras**
> > 
> > * [ ]   Attacks
> > * [ ]   Item Collection (inventory or picking up potions as you go)
> > * [ ]   Abilities
> > 
> > Note. These are tasks that are deemed extras as they are not as essential currently for the game to at least function and be playable. These will be targeted if time permits and all core tasks are completed.
> > # **Documentation**
> > 
> > * To be updated
> > 
> > # **Members**
> > 
> > * Caitlin Thompson (@tommps) (Caitlin)
> > * Eric Cheong Kai Kit (@25Ericcheong) (Eric)
> > * Jing Yang (@ydiannaj)
> > * Lucas Bouwman (@Bluehalomango)
> > * Sambit Bhattacharya (@SBHATTA19)
> > * Aditya Singh Cheema (@addiii4)

Hi @addiii4, I saw you added yourself to the member list of this team. I'm pretty sure you are part of Studio 2 External - Team 2. This is Studio 6 Internal - Team 2's feature ticket. Please let me know if there is any confusion.

**Comment by tommps** [comment]
End of sprint 1
