### ISSUE TITLE
Sprint 2 Team 3: The Darkness

### ISSUE THREAD

**Issue by yourlow** [UQdeco2800/2021-studio-6#80]
# **Description**
The Darkness is a feature built into the story and the world of the game. It is an everpresent thing in the game which will be the main draw and kind of game loop, escape the darkness get to the light.

 The darkness consist of two parts a visual element and a gameplay element. The visual element will be the physical lighting of the game areas, This will give the game environments atmosphere by making things darker and interactivity by making the lighting dynamic.  Still to be fleshed out but the darkness will affect parameters on either the player or the enemies.

## SubFeature/component (optional)
**Design of darkness
Lighting Engine
Gameplay implementation (collisions etc...)** 

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Basic integration with lighting 5 Sep
- [x] Creation of lighting engine (similar to renderable) 7th Sep
- [ ] First draft of lighting gameplay 9th Sep
- [ ] Gather feedback from studio 10th Sep
- [ ] Iterate and improve upon darkness

**Completion Deadline:** 17th Sep

# **Documentation**
Lighting Wiki
Darkness gameplay Wiki

# **Members**
- Matt (@yourlow) (Matthew Holloway)
