### ISSUE TITLE
Player Task: Overhaul Melee Implementation

### ISSUE THREAD

**Issue by Bluehalomango** [UQdeco2800/2021-studio-6#81]
# **Description**
**Task:** [Overhaul Melee Implementation](#).
**Feature:** [#61]
 
While a melee attack was created and implemented in Sprint 1, there are currently several components of it that stand to benefit from an overhaul and improvement. The first feature of this revamp is to change the current melee attack to a more directional-based attack instead of all around the player. This will follow the example left by ranged attack and make use of the four movement directions to specify the quadrants that should be covered by an attack.

The secondary feature is to create a more modular and extensibile melee component. This is mainly for use later in development by specialising it with different types of melee weapons that feature different characteristics to each other but still share the same base functionality. Specifically, this covers the dependency that the 3 additional melee weapons have later in this sprint.
 
## **Example**
- **Directional Attack**: After moving left last, the melee attack will be focused in that direction and only affect enemies in that area.
- **Extensible Melee Component**: The base melee attack component can be extended to create different weapon types and classes with unique behaviours, such as a sword, axe, dagger, etc.
  
# **Milestones**
List of steps that need to be completed for this task.
- [x] Initial Documentation(06/09)
- [x] Finish directional melee implementation from Sprint 1 (06/09)
- [x] Change MeleeAttackComponent to make use of passed variables instead of static values (07/09)
- [x] Mock and Unit tests  (08/09)
- [x] Final Documentation(08/09)
 
**Completion Deadline:** 08/09
  
# **Documentation**
- [Player Health System](../../2021-studio-6/wiki/Player-Attacks)
 
# **Member**
- Lucas Bouwman (@Bluehalomango)
