### ISSUE TITLE
Enemies Task: Tougher Long Range Enemy

### ISSUE THREAD

**Issue by yourlow** [UQdeco2800/2021-studio-6#83]
# **Description**
**Task:** Tougher Long Range Enemy.
**Feature:** Sprint 2 Enemies(#80)

We currently have a enemy sprite and animation for another ranged enemy, last sprint this was going to be a short range enemy, however we have changed our minds and believe this should be a tougher long range enemy. The current idea is for this enemy to fire 3 projectiles (see image below)

![traj](https://user-images.githubusercontent.com/22719803/132122483-f73d9b47-2224-432e-9c10-a9de6627cb99.png)

This enemy will essentially be a copy paste of the long range enemy entity. However the bullet AI will need to be changed. Currently  the `FireBulletListener` class actually spawns the bullet entity into the game world (look at the `FireBulletListener.fire()` method. You will need to make a different class which essentially does the same thing (say `ToughFireBulletLIstener`) but is going to call a different method in `EnemyBulletFactory` and is going to delegate spawning the bullet into `EnemyBulletFactory` (this should be alright because `EnemyBulletFactory` already takes a reference to `GameArea`).

 In `EnemyBulletFactory` you will need to modify the code to fire 3 bullets with offset angles, you will need to take `newTarget` and rotate it by +45 degress and - 45 degrees, this article should show you the formula you need to do this https://matthew-brett.github.io/teaching/rotation_2d.html

specifcally this one 

![image](https://user-images.githubusercontent.com/22719803/132123186-498a30b3-8493-4266-8cae-e9cc211bd4ca.png)

There may be more to this ticket than just that but have a crack at it
 

# **Dependencies**

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Create new Listener (Sep 7th)
- [x] Create new factory method (Sep 7th)
- [x] Factory spawning 3 bullets (Sep 7th)
- [x] Factory rotating bullet properly (Sep 10th)

 
**Completion Deadline:** 10 Sep

 
# **Documentation**

 
# **Member**
- @nikmatha
