### ISSUE TITLE
Player Task: Ammo to long ranged attack

### ISSUE THREAD

**Issue by 25Ericcheong** [UQdeco2800/2021-studio-6#85]
# **Description**
**Task:** #85  
**Feature:** #61 
 
Currently, player can shoot bullets without any limits in placed - making it too easy for player to range attack enemies very easily throughout the game.  A solution to this is to limit the number of bullets player can shoot by tracking the number of bullets player has based on inventory. Player will need to 'reload' or at least have enough ammo in inventory for such range attack to be executable in game. 
 
## **Example**
- **Ammo**: Player will need to have sufficient ammo to reload bullets
- **Firing 5 shots**: After firing 5 shots, player will require to reload bullets and this will deplete number of ammo count in inventory
 
# **Dependencies**
- [ ] Pickup item component
 
# **Milestones**
- [x] Initial documentation (06/09)
- [x] Track ammo count from inventory. If player tries to shoot when there is no ammo in magazine - nothing will happen (07/09)
- [x] Reloading will not fill bullet magazine when there is no ammo in inventory (07/09)
- [x] Allow player to reload [this reloads bullets for range attack to maximum of 5 again]. If player tries to fire bullets, nothing will happen during the duration of reloading. (07/09)
- [x] Unit testing (08/09) 
 
**Completion Deadline:** Sept. 8
 
# **Documentation**
- [Wiki ](https://github.com/UQdeco2800/2021-studio-6/wiki/Player-Attacks)
 
# **Member**
- @25Ericcheong
