### ISSUE TITLE
Enemies Task: New Enemy (Spawner)

### ISSUE THREAD

**Issue by Hamish-Killen** [UQdeco2800/2021-studio-6#86]
# Description
The Spawner enemy will not move, but will spawn small enemies until it is killed. The enemy will also have a much longer range at which it can detect the player.

Feature: #55 

# Milestones
Programming
- [x] Placeholder sprite
- [x] Spawning new enemy
- [x] Eliminate movement for new enemy
- [x] Increased player detection range
- [x] Spawning smaller enemies

Design
- [x] Static sprite
- [x] Idle animation

# Documentation

# Extras
- [ ] Animation when spawning enemies

# Members
@Hamish-Killen 
@Hollycatsoulis
