### ISSUE TITLE
Player Task: Health and dash cooldown interface

### ISSUE THREAD

**Issue by 25Ericcheong** [UQdeco2800/2021-studio-6#87]
# **Description**
**Task:**  #87 
**Feature:** #61 
 
Currently, there are HUDs already designed (for health and dash cooldown) to be displayed in game for player to observe. However, these are not yet incorporated in a way that responds to the player's health and dash cooldown duration. These will now be implemented so that player can easily visualize what is happening to their health and whether they can dash currently in game as well. 

## **Example**
- **Health interface**: HUD pushed in game will need to change according to player's current health status. This will need to logically and accurately fit with how the current wound system is in placed for player and should still make sense to the user as they play the game. 
- **Dash cooldown interface**: After dash is used, bars will need to be reflected in a way that informs user of current status of dash cooldown and when it is ready to be used again - it should be visually shown to be in a way that is easy for user to interpret as well. This will be implemented with timer set for how long it takes for dash to be usable once again.
 
# **Milestones**
- [x] Initial documentation (07/09)
- [x] Understand how atlas file works in parallel with current wound system in placed for player (07/09)
- [x] Manipulate atlas file to visually be changed when player receives damage (07/09)
- [x] Ensure health bar HUD is smooth and logical when player receives damage and regen (08/09)
- [x] Dash cooldown interface will be implemented the same way as well and coherently (08/09)
- [x] Get Interface Animations to Appear at game start (10/09)
- [x] Modify IndependentAnimator to be able to set coordinates
- [x] Final documentation (10/09)
 
**Completion Deadline:** Sept. 8
 
# **Documentation**
- [Wiki for health ](https://github.com/UQdeco2800/2021-studio-6/wiki/Player-Health)
- [Wiki for dash ](https://github.com/UQdeco2800/2021-studio-6/wiki/Player-Movement)
 
# **Member**
- @25Ericcheong 
- @Bluehalomango
