### ISSUE TITLE
Player Task: Inventory HUD

### ISSUE THREAD

**Issue by SBHATTA19** [UQdeco2800/2021-studio-6#89]
# **Description**
**Task:** Inventory HUD
**Feature:** [#68 ]
 
Player interface that displays the various consumables as well as amounts and hotkeys for each of them. The inventory HUD will be used to display the primary usable items that will grant the player special abilities. 
 
## **Example**
- **Bandage:** The player will be able to use the bandage in order to heal their wounds. 
  
# **Milestones**
- [x] Initial display implementation (8/09)
- [x] Integration with player to enable usability (14/09)
- [x]  Testing abilities and usage of items(15/09)
 
**Completion Deadline:** 14/09
  
# **Documentation**
- [Player Abilities](../../2021-studio-6/wiki/Player-Abilities)

# **Dependencies**
- #62 Finalised HUD depends on the design and creation of item assets
 
# **Member**
- Sambit Bhattacharya (@SBHATTA19)

**Comment by 25Ericcheong** [comment]
Already implemented, if you press the button 1 - bandage will be used (only when there is bandage in inventory and wound state is lesser than 3). It is also shown in inventory HUD
