### ISSUE TITLE
Sprint 1 Team 1: Interface Feature

### ISSUE THREAD

**Issue by implex001** [UQdeco2800/2021-studio-6#9]
# **Interface Feature**
In this sprint, we will be implementing the user interface elements for the game. This will involve setting up game menus, as well as displaying player information during gameplay (HUD).

Additionally, we will write a small story prompt and a mechanism for displaying it to the player for the prologue and throughout the gameplay.

### Title Screen
First window that loads up when player runs the game
- Play game
- Settings
- Quit game

### Heads up display (HUD)
- Bars and status effects: Information that should be available in the main gameplay screen.
- Health Bar: Bar representing remaining amount of health
- Environment details

#### Examples
- Health Bar: When the player takes damage from an enemy, the health bar on the HUD decreases in value. (displayed in hearts or a line e.g)
- Environment details: When a player reaches the next level/area then the new level/area is displayed on the HUD.

### Pause menu
In-game menu that the player can access to restart the game/level, quit the game, or change settings by accessing the settings menu.

#### Examples
- Menu: Pop-up menu appears if the player hits the ESC key. This would pause the game and show options, for example "Quit".

### Settings menu
The menu interface that holds all the settings available. Accessible from both the title screen and the pause menu.

#### Volume Options
Options that allow the player to control the volume
- Master Volume: Variable that controls all volume type
- Music Volume
- Sound Effects Volume
- Ambient Sound Volume

#### Screen Options
Options that allow the player to control the screen size and or fullscreen/windowed mode
- Screen resolution / ratio
- Fullscreen / windowed mode
- VSync

#### Controls Configuration
Allows the player to change controls used in the game and to view them.
- Initialize default configuration
- Player sets configuration and way for them to save the configuration to future execution of the game.
- Reset configuration to default configuration
- Disallow overlapping controls
- Link the configuration to the player controls.

### Dialogue Box Shell
Dialogue box functionality to allow for text that appears in game to add context to the storyline of the game as well as react to the player’s interaction with the game environment and characters.

#### Examples
- Dialogue: As the player starts the game a prologue of text explaining the storyline will be displayed. The player can advance the text by pressing `SPACEBAR`, similar to many role-playing computer games.

# **Dependencies**
- [x] HUD: Data structures for the player are implemented and relevant data is accessible through getter methods. #8
- [x] HUD: Data structures representing environment information to be displayed to the player are implemented implemented and relevant data is accessible through getter methods. #11
- [ ] Pause menu: The ability to pause the timeflow of the game. #7 

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] #12
- [x] #14
- [ ] #15

**Completion Deadline:** Thursday 2 September 2021, 4:00pm

# **Extras (optional)**
- [ ] Pause menu
- [ ] Settings menu
- [ ] Player stats, including health bar
- [ ] Environment stats
- [ ] HUD visual change when player is low on health
- [ ] Prologue scene dialogue and visuals

# **Documentation**
- [Title Screen](https://github.com/UQdeco2800/2021-studio-6/wiki/Title-Screen)
- [HUD Design Documentation](https://github.com/UQdeco2800/2021-studio-6/wiki/HUD-Design-Documentation)
- [Dialogue Boxes](https://github.com/UQdeco2800/2021-studio-6/wiki/Dialogue-Boxes)
- [Art Direction](https://github.com/UQdeco2800/2021-studio-6/wiki/Art-Direction)

# **Members**
(Name, GitHub, Discord)
- Brian Stewart (@DancingBrian) (Brian#8636)
- Chris Kang (@Skybluepanda) (@Bluepanda#5218)
- Laura Johnston (@ScariestWheat) (ScariestWheat#5492)
- Renée (@NightingaleUQ) (Renée)
- Joseph (@implex001) (implex001#2331)
