### ISSUE TITLE
Player Task: Pickup Item Component

### ISSUE THREAD

**Issue by ultimate1112** [UQdeco2800/2021-studio-6#90]
# **Description**
**Task:** Item Management
**Feature:** [#68]
 
Items are **consumables** that the player can pick up and use in the game. Player will only be able to pick items up when colliding with them in the game world. Only selected type of item (entity based) can be picked up my player. For this sprint, bandages, coins and ammo can be picked up. Process is when an enemy dies, ammo or coins will be dropped and player will then be able to pick these up. For this sprint, these items will be spawned randomly in the first level of the game for testing purposes. Coins can be used for purchasing and ammo can be used for range attack (since it is now limited to number of ammo player currently has). Bandages can be used to heal wound state of player by 1. 
The visual interface / HUD for this ticket is [#89].
 
## **Example**
- **Picking items up:** Only 3 types of items can be picked up during the game. Any other collision with any other entity in the game will be ignored and will not be picked up by player. 
- **Post item pickups:** Items that are picked up must visibly be shown on the player's HUD so user will acknowledge and is made known that an item has been picked up. This is crucial.
  
# **Milestones**
- [x] Prepare relevant classes/components related to item pick up behavior - ENUMS (for different item types), ItemComponent (to designate relevant variables for identification when item is picked up) and ItemFactory (to spawn items in game world for picking up)
- [x] Player should only be allowed to pick up certain type of items (13/09)
- [x] Colliding with items that can be picked up can visibly be shown to have disappeared from game world (indicating that it has been picked up) (13/09)
- [x] Items picked up will be registered and data will be updated in inventory component. (14/09)
- [x] Updated data will be shown on the player's HUD (14/09)
- [x] Documentation (15/09)
- [x] Unit testing (15/09)
 
**Completion Deadline:** Sept. 17
  
# **Documentation**
- [Wiki ](https://github.com/UQdeco2800/2021-studio-6/wiki/Player-Inventory-and-Pickup-Items)  

# **Dependencies**
- #96 
- #89 
 
# **Member**
- Anthony Chiam (@ultimate1112)
- Eric Cheong Kai Kit (@25Ericcheong) (Eric)
