### ISSUE TITLE
Player Task: Item Reusable Components

### ISSUE THREAD

**Issue by 25Ericcheong** [UQdeco2800/2021-studio-6#96]
# **Description**
**Task:** #96  
**Feature:** #68  
 
An additional component will be created to allow player to use (repeatedly if needed) items that are picked up throughout the game or items that are given at the start of the game. Currently, for this sprint, only bandages would be reusable and this can be used via numbered keys and will be shown on the player's HUD. This component will be used to trigger events based on items available in the inventory (for this sprint, only bandages) when a numbered key is pressed. This component will be expanded to trigger different things which will/can affect player's health, speed etc. 
 
## **Example**
- **Using an Item**: For this sprint, only bandage would be a reusable item - but this can expand to many different items in the next sprint. If a bandage is used, player's health will increase and this should be visibly seen on the player's HUD and the number of bandage item quantity should visibly be shown to decrease as well.
- **Effects**: As mentioned, when an item is used. Effect should visibly be shown and applied on player. It is also worth mentioning that if item quantity is 0, no effect will be applied to player when key is pressed. 
 
# **Dependencies**
- #90 
- #89 
 
# **Milestones**
- [x] Update inventory component to have bandage count in placed (10/09)
- [x] Increase player's wound state when hotkey is pressed (in this case - 1 is the key) (11/09)
- [x] If player's wound state is full, do nothing and if there are no bandages in inventory - nothing will happen (11/09)
- [x] When a bandage is used, decrease number of bandage left in inventory. (12/09)
- [x] Ensure any items used (or not) will be displayed on player's HUD correctly. (12/09)
- [x] Documentation (15/09) 
- [x] Unit testing (15/09)
 
**Completion Deadline:** Sept. 17
 
# **Documentation**
- [Wiki ](https://github.com/UQdeco2800/2021-studio-6/wiki/Player-Inventory-and-Pickup-Items)  
 
# **Member**
- @25Ericcheong
