### ISSUE TITLE
Player Task: Info on Reloading & Magazine count

### ISSUE THREAD

**Issue by 25Ericcheong** [UQdeco2800/2021-studio-6#99]
# **Description**
Player can only shoot 5 times before having to reload (which takes ammo out from inventory and if there is no ammo from inventory, nothing happens). There is no visible sign of the number of magazine capacity of gun currently (this decreases when bullet is fired) along with no feedback on whether gun is currently reloading or has it already reloaded (this happens when R is clicked). Lastly, there is no information on whether magazine of gun is empty which may confuse users when playing the game.
 
## **Examples**
- **Info on magazine count:** Should provide visible information on number of bullets left in current gun magazine. This can be used as a source for user to keep track of number of bullets left in gun magazine currently
- **Reloading information:** To provide feedback to user when it is time to reload (in reality user can reload whenever gun magazine capacity is < 5 but when it reaches zero - a popup will appear). This information will be provided when user has run out of bullets to shoot and at the same time it will notify user when gun is currently reloading after user has pressed the R key. 

# **Dependencies**
- #85 Need to keep track of gun magazine of player to be displayed on screen
 
# **Milestones**
- [x] Revamp how reloading has been implemented. It runs on a timer now but a better alternative can be used instead to make testing doable (11/09)
- [x] Display information on number of magazine count for user to visibly see bullets left to shoot before reloading (using images) (11/09)
- [x] A popup text (label) should be displayed on screen when magazine count is 0 (11/09)
- [x] A new and different popup text should be shown on the screen when gun is currently reloading for user's information (12/09)
- [x] Once reloading finishes, gun magazine count should be updated visibly (12/09)
- [x] Reloading information should no longer be visible once reloading has finished (13/09)
- [x] Documentation (14/09)
- [x] Unit testing (14/09)

Sprint Due date = 16/09

# **Documentation**
- [Wiki ](https://github.com/UQdeco2800/2021-studio-6/wiki/Player-Attacks)
 
# **Members**
- Eric Cheong Kai Kit (@25Ericcheong) (Eric)
